// ── CODEX MASTER DATA — comprehensive descriptions for every glossary item ──

export const CODEX_ZODIAC: { name: string; icon: string; tag: string; short: string; long: string }[] = [
  { name: "Aries", icon: "♈", tag: "The Pioneer", short: "🔥 Bold, ambitious, first to act.", long: "Aries is the first sign of the zodiac, ruled by Mars — the planet of drive and action. Arians are natural initiators: bold, energetic, and fearless when starting new projects. They thrive on competition and love being first. In creative work, Aries brings momentum, courage, and a let's-go energy that gets things moving. They can be impatient and impulsive, but their enthusiasm is infectious. Best collabs: Leo, Sagittarius, Gemini, Aquarius." },
  { name: "Taurus", icon: "♉", tag: "The Builder", short: "🌍 Reliable, patient, quality-first.", long: "Ruled by Venus, Taurus is grounded, sensual, and deeply committed to craft. Taureans value quality over quantity and have extraordinary patience — they'll polish a single frame until it's perfect. They're dependable collaborators who finish what they start and bring a calm, steadying presence to any set. Stubborn at times, but their loyalty and aesthetic sense are unmatched. Best collabs: Virgo, Capricorn, Cancer, Pisces." },
  { name: "Gemini", icon: "♊", tag: "The Communicator", short: "💨 Versatile, witty, expressive.", long: "Ruled by Mercury, Gemini is the zodiac's communicator — quick-witted, curious, and endlessly adaptable. Geminis juggle multiple ideas at once and thrive on variety and conversation. In creative work they're versatile, bringing fresh perspectives and rapid-fire ideas. They excel in writing, performance, and anything involving words and connection. Can be scattered, but their mental agility makes them brilliant brainstormers. Best collabs: Libra, Aquarius, Aries, Leo." },
  { name: "Cancer", icon: "♋", tag: "The Nurturer", short: "💧 Intuitive, emotional, protective.", long: "Ruled by the Moon, Cancer is intuitive, nurturing, and deeply in touch with emotion. Cancers create safe, supportive environments where collaborators feel protected and free to be vulnerable. Their emotional intelligence makes them exceptional at work that needs depth and heart — portraiture, documentary, and human storytelling. They remember every detail and care deeply about the people they work with. Best collabs: Scorpio, Pisces, Taurus, Virgo." },
  { name: "Leo", icon: "♌", tag: "The Performer", short: "🔥 Creative, generous, a star.", long: "Ruled by the Sun, Leo is the natural performer of the zodiac — creative, passionate, and generous with their light. Leos love the spotlight and bring warmth, confidence, and theatrical flair to everything they do. They're inspiring collaborators who elevate everyone around them and demand excellence. Their pride can be a challenge, but their heart and artistry are undeniable. Best collabs: Aries, Sagittarius, Gemini, Libra." },
  { name: "Virgo", icon: "♍", tag: "The Analyst", short: "🌍 Precise, practical, detailed.", long: "Ruled by Mercury, Virgo is analytical, precise, and relentlessly detail-oriented. Virgos are the perfectionists of the zodiac — they notice the 1% flaws no one else sees and fix them. In creative work they bring editorial rigor, flawless technique, and an unmatched work ethic. They're humble and service-oriented, quietly making everything better. Can over-critique, but their craftsmanship is peerless. Best collabs: Taurus, Capricorn, Cancer, Scorpio." },
  { name: "Libra", icon: "♎", tag: "The Diplomat", short: "💨 Balanced, social, artistic.", long: "Ruled by Venus, Libra is balanced, social, and exquisitely attuned to beauty and harmony. Librans see aesthetics everywhere and have an innate sense of composition, style, and proportion. They're natural diplomats who keep teams in harmony and mediate conflict gracefully. In creative work they excel at anything visual — design, fashion, art direction. They can be indecisive, but their taste is flawless. Best collabs: Gemini, Aquarius, Aries, Sagittarius." },
  { name: "Scorpio", icon: "♏", tag: "The Strategist", short: "💧 Intense, brave, transformative.", long: "Ruled by Pluto and Mars, Scorpio is intense, resourceful, and profoundly passionate. Scorpios commit completely — their focus and depth are unmatched. They're drawn to the dark, the mysterious, and the transformative. In creative work they bring emotional intensity and a fearless willingness to go where others won't. They're loyal to the end but demand authenticity. Best collabs: Cancer, Pisces, Taurus, Capricorn." },
  { name: "Sagittarius", icon: "♐", tag: "The Explorer", short: "🔥 Adventurous, idealistic, free.", long: "Ruled by Jupiter, Sagittarius is the zodiac's explorer — generous, idealistic, and hungry for adventure and meaning. Sagittarians push creative boundaries and hate being confined. They bring optimism, humor, and a big-picture vision that inspires collaborators to dream bigger. Their restlessness can make follow-through a challenge, but their enthusiasm and wisdom are magnetic. Best collabs: Aries, Leo, Gemini, Libra." },
  { name: "Capricorn", icon: "♑", tag: "The Achiever", short: "🌍 Disciplined, ambitious, builder.", long: "Ruled by Saturn, Capricorn is disciplined, ambitious, and relentlessly goal-oriented. Capricorns build things that last — they have the patience and strategy to turn vision into institutions. In creative work they're the ones who deliver on time, on budget, every time, without drama. They respect craft and earned success. Can be serious, but their reliability is gold. Best collabs: Taurus, Virgo, Cancer, Scorpio." },
  { name: "Aquarius", icon: "♒", tag: "The Visionary", short: "💨 Original, progressive, independent.", long: "Ruled by Uranus, Aquarius is the zodiac's visionary — original, progressive, and fiercely independent. Aquarians think decades ahead and invent new creative forms before anyone else. They champion causes, embrace technology, and reject convention. In creative work they bring radical originality and a collaborative, egalitarian spirit. Can be aloof, but their genius is real. Best collabs: Gemini, Libra, Aries, Sagittarius." },
  { name: "Pisces", icon: "♓", tag: "The Dreamer", short: "💧 Artistic, intuitive, boundless.", long: "Ruled by Neptune, Pisces is the dreamer and mystic of the zodiac — compassionate, artistic, and deeply intuitive. Pisceans feel everything and translate raw emotion into transcendent art. They have no creative boundaries and can imagine anything. In collaboration they're selfless, empathetic, and attuned to the group's emotional current. Can struggle with boundaries, but their imagination is the soul of any project. Best collabs: Cancer, Scorpio, Taurus, Virgo." },
];

export const CODEX_CHINESE: { name: string; icon: string; short: string; long: string }[] = [
  { name: "Rat", icon: "🐀", short: "Quick-witted, resourceful.", long: "The Rat is the first animal of the Chinese zodiac, symbolizing intelligence and adaptability. Rats are quick-witted, resourceful, and see opportunity everywhere — they move fast and land on their feet. In creative work they're clever problem-solvers who can pivot on a dime. Natural networkers with sharp instincts." },
  { name: "Ox", icon: "🐂", short: "Steadfast, reliable.", long: "The Ox symbolizes diligence and dependability. Ox people are steady, methodical, and incredibly hard-working — the dependable workhorse who never quits. They build careers through patient, consistent effort and are trusted collaborators who always deliver." },
  { name: "Tiger", icon: "🐅", short: "Courageous, magnetic.", long: "The Tiger represents courage and charisma. Tigers are bold, competitive, and magnetic — they bring fearless energy to everything they touch and are natural-born leaders. Their confidence inspires others to take risks." },
  { name: "Rabbit", icon: "🐇", short: "Graceful, diplomatic.", long: "The Rabbit symbolizes gentleness and grace. Rabbit people are elegant, diplomatic, and prefer harmony over conflict. They bring quiet excellence and refined taste to creative work, excelling in detail and aesthetics." },
  { name: "Dragon", icon: "🐉", short: "Charismatic, ambitious.", long: "The Dragon is the most powerful sign, symbolizing luck and ambition. Dragons are charismatic, confident, and destined for big things — natural showstoppers who lead with flair. Their drive and magnetism make them magnetic collaborators." },
  { name: "Snake", icon: "🐍", short: "Wise, intuitive.", long: "The Snake symbolizes wisdom and intuition. Snake people are deep thinkers who move with calculated precision. They're enigmatic, philosophical, and see beneath the surface — bringing strategic depth to creative projects." },
  { name: "Horse", icon: "🐴", short: "Energetic, independent.", long: "The Horse symbolizes freedom and energy. Horse people are energetic, independent, and spirited — they chase adventure and can't be contained. Their enthusiasm and speed make them exciting, if restless, collaborators." },
  { name: "Goat", icon: "🐐", short: "Creative, gentle.", long: "The Goat (or Sheep) symbolizes peace and creativity. Goat people are gentle, artistic, and nurturing — they create beauty and calm wherever they go. Their sensitivity makes them exceptional at emotive, human-centered work." },
  { name: "Monkey", icon: "🐒", short: "Clever, inventive.", long: "The Monkey symbolizes wit and invention. Monkey people are clever, playful, and endlessly inventive — they find unconventional solutions and keep things fun. Their humor and ingenuity light up any collaboration." },
  { name: "Rooster", icon: "🐓", short: "Confident, exacting.", long: "The Rooster symbolizes confidence and precision. Rooster people are observant, exacting, and proud of their craft. They're detail-obsessed perfectionists who bring polish and punctuality to every project." },
  { name: "Dog", icon: "🐕", short: "Loyal, honest.", long: "The Dog symbolizes loyalty and integrity. Dog people are honest, protective, and fiercely loyal — the collaborator you can always count on. They bring trust, warmth, and a strong moral compass to creative teams." },
  { name: "Pig", icon: "🐖", short: "Generous, sincere.", long: "The Pig symbolizes generosity and sincerity. Pig people are warm, genuine, and whole-hearted — they bring authenticity and abundance to everything they do. Their kindness makes them beloved collaborators." },
];

export const CODEX_LIFE_PATH: { n: number; title: string; long: string }[] = [
  { n: 1, title: "The Leader", long: "Life Path 1 is the pioneer — independent, ambitious, and a born initiator. Ones are here to lead, create, and break new ground. They hate being told what to do and excel when given autonomy. In creative work they're the ones who start movements, launch projects, and set the direction. Their challenge is learning to collaborate without dominating." },
  { n: 2, title: "The Diplomat", long: "Life Path 2 is the peacemaker — sensitive, cooperative, and deeply intuitive. Twos are the glue of any collaboration, sensing emotional undercurrents and bringing harmony. They excel at partnership, mediation, and anything requiring tact. Their challenge is setting boundaries and not losing themselves in others." },
  { n: 3, title: "The Creative", long: "Life Path 3 is the expressive artist — joyful, communicative, and born to create. Threes are the natural writers, performers, and visual artists of numerology. They process the world through expression and bring lightness and humor. Their challenge is focus and finishing what they start." },
  { n: 4, title: "The Builder", long: "Life Path 4 is the master builder — disciplined, reliable, and grounded. Fours turn vision into durable, tangible work through patience and systems. They're the ones who make ideas real and lasting. Their challenge is flexibility and trusting the unknown." },
  { n: 5, title: "The Freedom Seeker", long: "Life Path 5 is the adventurer — versatile, restless, and drawn to change. Fives thrive on variety, travel, and bold experimentation. They bring energy and adaptability to every project. Their challenge is commitment and seeing things through." },
  { n: 6, title: "The Nurturer", long: "Life Path 6 is the caregiver — responsible, loving, and devoted. Sixes make collaborators feel supported, safe, and valued. They bring warmth and a strong sense of responsibility to every team. Their challenge is over-giving and perfectionism." },
  { n: 7, title: "The Seeker", long: "Life Path 7 is the mystic — analytical, introspective, and drawn to deeper truth. Sevens dig beneath the surface and bring depth, research, and wisdom to creative work. They excel at concept and meaning. Their challenge is connecting with the outer world." },
  { n: 8, title: "The Powerhouse", long: "Life Path 8 is the executive — driven, commanding, and built for achievement. Eights channel ambition into real-world success and understand power, money, and influence. They're natural producers and leaders. Their challenge is balancing material success with heart." },
  { n: 9, title: "The Humanitarian", long: "Life Path 9 is the visionary — compassionate, wise, and globally minded. Nines create work that serves a larger purpose and inspires change. They bring idealism and empathy to everything. Their challenge is letting go and completing cycles." },
  { n: 11, title: "The Illuminator (Master Number)", long: "Life Path 11 is a Master Number — intensely intuitive, inspired, and a conduit for visionary ideas. Elevens operate at a higher frequency and bring spiritual depth and genius insight. Their challenge is grounding their gifts and managing sensitivity." },
  { n: 22, title: "The Master Builder (Master Number)", long: "Life Path 22 is the most powerful number — the Master Builder who dreams on a world-changing scale and has the discipline to actually build it. Twenty-twos combine vision with execution to create lasting legacy. Their challenge is the enormous weight of their own potential." },
  { n: 33, title: "The Master Teacher (Master Number)", long: "Life Path 33 is the rarest Master Number — the Master Teacher, a healer-mentor who elevates everyone around them. Thirty-threes embody unconditional love and service, guiding others to their highest expression. Their challenge is self-care while serving." },
];

export const CODEX_MBTI: { code: string; tag: string; short: string; long: string; best: string }[] = [
  { code: "INTJ", tag: "The Architect", short: "Strategic, independent, future-focused.", long: "INTJs are rare, visionary strategists. They see patterns others miss and build airtight long-term plans. Independent and analytical, they prefer working alone but lead brilliantly when needed. In creative work they're the master planners and conceptual architects. They can seem aloof but are deeply loyal. Best collabs: ENTP, ENFP.", best: "ENTP, ENFP" },
  { code: "INTP", tag: "The Logician", short: "Inventive, analytical, curious.", long: "INTPs are the theorists — endlessly curious, inventive, and precise. They deconstruct ideas to their bones and rebuild them better. They thrive on intellectual challenge and bring groundbreaking concepts to creative work. Best collabs: ENTJ, ENFJ.", best: "ENTJ, ENFJ" },
  { code: "ENTJ", tag: "The Commander", short: "Bold, decisive, a leader.", long: "ENTJs are natural leaders — bold, decisive, and relentlessly efficient. They rally teams, set ambitious goals, and drive projects to completion on schedule. In creative work they're the directors and producers who make things happen. Best collabs: INTP, INFP.", best: "INTP, INFP" },
  { code: "ENTP", tag: "The Debater", short: "Witty, inventive, idea-generator.", long: "ENTPs are quick-witted idea generators who thrive on challenge and debate. They spark innovation through argument and exploration, seeing possibilities everywhere. They bring energy and unconventional brilliance to every project. Best collabs: INTJ, INFJ.", best: "INTJ, INFJ" },
  { code: "INFJ", tag: "The Advocate", short: "Visionary, principled, quiet.", long: "INFJs are quiet visionaries guided by strong principles. They craft deep meaning and pursue causes with quiet intensity. Their rare combination of insight and empathy makes them transformative collaborators. Best collabs: ENFP, ENTP.", best: "ENFP, ENTP" },
  { code: "INFP", tag: "The Mediator", short: "Idealistic, creative, authentic.", long: "INFPs are idealistic creatives driven by authentic values. They translate emotion and imagination into deeply original work. Gentle but principled, they bring soul and integrity to collaboration. Best collabs: ENFJ, ENTJ.", best: "ENFJ, ENTJ" },
  { code: "ENFJ", tag: "The Protagonist", short: "Charismatic, empathetic leader.", long: "ENFJs are charismatic, empathetic leaders who bring out the best in people. They make collaborators feel seen, valued, and inspired. Natural mentors and motivators, they excel at creative direction. Best collabs: INFP, INTP.", best: "INFP, INTP" },
  { code: "ENFP", tag: "The Campaigner", short: "Enthusiastic, spontaneous, social.", long: "ENFPs are enthusiastic, spontaneous free spirits who ignite possibility everywhere. They're creative chameleons, full of warmth and new ideas. Their energy and empathy make them magnetic collaborators. Best collabs: INFJ, INTJ.", best: "INFJ, INTJ" },
  { code: "ISTJ", tag: "The Logistician", short: "Dependable, detailed, organized.", long: "ISTJs are dependable, detail-oriented, and deeply organized. They deliver flawless execution and honor every commitment with integrity. In creative work they're the rock-solid production backbone. Best collabs: ESFP, ESTP.", best: "ESFP, ESTP" },
  { code: "ISFJ", tag: "The Defender", short: "Warm, meticulous, protective.", long: "ISFJs are warm, meticulous, and quietly protective. They're the reliable backbone of any crew — conscientious, detail-driven, and deeply caring. They bring stability and heart to every project. Best collabs: ESFP, ESTP.", best: "ESFP, ESTP" },
  { code: "ESTJ", tag: "The Executive", short: "Efficient, organized, decisive.", long: "ESTJs are efficient organizers who turn plans into reality. They run tight, productive productions with clear systems and high standards. Their leadership and reliability make them invaluable on set. Best collabs: ISFP, ISTP.", best: "ISFP, ISTP" },
  { code: "ESFJ", tag: "The Consul", short: "Harmonious, people-first.", long: "ESFJs are harmonious, people-first collaborators who keep teams connected and morale high. They're conscientious, warm, and excellent at coordination. They excel at client relations and team culture. Best collabs: ISFP, ISTP.", best: "ISFP, ISTP" },
  { code: "ISTP", tag: "The Virtuoso", short: "Hands-on, calm, master tooler.", long: "ISTPs are hands-on virtuosos — cool under pressure and masterful with tools and technique. They solve problems on the fly with calm precision. In creative work they're the technical wizards. Best collabs: ESFJ, ESTJ.", best: "ESFJ, ESTJ" },
  { code: "ISFP", tag: "The Adventurer", short: "Artistic, spontaneous, sensory.", long: "ISFPs are artistic adventurers who live by aesthetics. They create beauty in the moment and have an innate eye for composition and craft. Quiet but deeply expressive, they bring authenticity to every frame. Best collabs: ESFJ, ESTJ.", best: "ESFJ, ESTJ" },
  { code: "ESTP", tag: "The Entrepreneur", short: "Bold, energetic, pragmatic.", long: "ESTPs are bold, energetic pragmatists who thrive on set. They make split-second decisions with flair and handle chaos gracefully. Their charisma and hands-on energy make them dynamic collaborators. Best collabs: ISTJ, ISFJ.", best: "ISTJ, ISFJ" },
  { code: "ESFP", tag: "The Entertainer", short: "Lively, expressive, magnetic.", long: "ESFPs are lively, expressive performers who bring the show — and the crowd. They're magnetic, spontaneous, and deeply attuned to the moment. They excel in performance and anything high-energy. Best collabs: ISTJ, ISFJ.", best: "ISTJ, ISFJ" },
];

export const CODEX_TYPES: { name: string; icon: string; long: string }[] = [
  { name: "Photographer", icon: "📷", long: "Captures still imagery across editorial, portrait, fashion, fine art, and commercial work. Photographers master light, composition, and camera craft to freeze moments into art." },
  { name: "Model", icon: "🧍", long: "The on-camera subject — runway, editorial, figure, and lifestyle. Models embody creative vision, using presence, poise, and expression to bring concepts to life." },
  { name: "Content Creator", icon: "🎥", long: "Produces social and digital content for brands and audiences. Content creators blend storytelling, editing, and platform fluency to build engaged followings." },
  { name: "Director", icon: "🎬", long: "Leads creative vision on set — film, music video, commercial, and experimental. Directors orchestrate cast, crew, and concept into a cohesive final piece." },
  { name: "Editor", icon: "✂️", long: "Post-production craft — cutting, pacing, color, VFX, and finishing. Editors shape raw footage into narrative, rhythm, and emotional impact." },
  { name: "MUA", icon: "💄", long: "Makeup Artist — transforms faces and bodies into art. MUAs design looks for editorial, beauty, film, and special effects, mastering color and contour." },
  { name: "Stylist", icon: "👗", long: "Curates wardrobe, props, and overall look — the aesthetic architect. Stylists translate concepts into visual language through fashion and detail." },
  { name: "Actor", icon: "🎭", long: "Performs character work across film, stage, and commercial. Actors embody emotion and story, bringing scripts to life with craft and vulnerability." },
  { name: "Videographer", icon: "📹", long: "Captures moving image — drone, gimbal, documentary, and event. Videographers master motion, stabilization, and real-time storytelling." },
  { name: "Writer", icon: "✍️", long: "Crafts narrative — scripts, copy, essays, and editorial prose. Writers shape ideas into words that move, persuade, and endure." },
  { name: "Producer", icon: "📋", long: "Makes it happen — funding, crew, schedule, and logistics. Producers turn creative vision into a financed, organized, deliverable reality." },
  { name: "Designer", icon: "🎨", long: "Shapes visual systems — branding, UI/UX, layout, and identity. Designers solve problems through typography, color, and form." },
];

export const CODEX_AESTHETICS: { name: string; long: string }[] = [
  { name: "Portrait", long: "Focused on the human subject — face, form, and expression. Portraiture seeks to reveal character, mood, and identity." },
  { name: "Editorial", long: "Magazine-style storytelling imagery with a narrative arc. Editorial work tells stories through sequenced, styled images." },
  { name: "Commercial", long: "Brand and advertising work built to sell a product or idea. Commercial imagery prioritizes clarity, appeal, and conversion." },
  { name: "Music Video", long: "Moving image synced to music, performance, and rhythm. Music videos blend cinematography with sound to create visceral experiences." },
  { name: "Documentary", long: "Real, unscripted storytelling — truth captured on camera. Documentary work bears witness with authenticity and integrity." },
  { name: "Branding", long: "Visual identity, logos, and cohesive brand systems. Branding builds recognition and meaning through consistent design language." },
  { name: "Body Art", long: "Fine-art figure and body-paint photography of the human form. Body art celebrates the body as canvas and sculpture." },
  { name: "Fine Art", long: "Gallery-intent imagery prioritizing concept and emotion over commerce. Fine art is personal, expressive, and boundary-defying." },
  { name: "Fashion", long: "Clothing, style, and runway-focused work. Fashion photography and film celebrate design, movement, and culture." },
  { name: "Experimental", long: "Boundary-pushing, unconventional approaches to image and film. Experimental work reinvents the medium itself." },
  { name: "Dark", long: "Moody, dramatic, low-key aesthetics with high contrast. Dark work explores shadow, tension, and atmosphere." },
  { name: "Dreamy", long: "Soft, ethereal, romantic visuals with hazy light. Dreamy work evokes nostalgia, fantasy, and softness." },
  { name: "Bold", long: "High-impact, saturated, unapologetically striking imagery. Bold work commands attention with color and confidence." },
  { name: "Vintage", long: "Retro, film-inspired aesthetics with nostalgic warmth. Vintage work channels the look of past eras." },
  { name: "Abstract", long: "Non-representational art focused on form, color, and texture. Abstract work prioritizes feeling over subject." },
  { name: "Film", long: "Motion-picture work — narrative, short, and feature film. Film is the fullest expression of moving-image storytelling." },
];
