// ── CODEX MASTER DATA — friendly descriptions for every glossary item ──

export const CODEX_ZODIAC: { name: string; icon: string; tag: string; short: string; long: string }[] = [
  { name: "Aries", icon: "♈", tag: "The Pioneer", short: "Bold, ambitious, first to act.", long: "Aries kicks off the zodiac, ruled by Mars, the planet of drive and action. Aries folks are bold, energetic, and fearless about starting new things. They love a challenge and being first. On a project they bring momentum, courage, and real get-it-done energy. They can rush things, but their excitement is contagious. They click best with Leo, Sagittarius, Gemini, and Aquarius." },
  { name: "Taurus", icon: "♉", tag: "The Builder", short: "Reliable, patient, all about quality.", long: "Taurus is ruled by Venus, so they're grounded, sensory, and serious about craft. They'd rather do one thing perfectly than ten things fast. They're the collaborator who finishes what they start and keeps everyone calm. A little stubborn at times, but their loyalty and taste are unbeatable. They click best with Virgo, Capricorn, Cancer, and Pisces." },
  { name: "Gemini", icon: "♊", tag: "The Communicator", short: "Versatile, witty, expressive.", long: "Gemini is ruled by Mercury, the planet of talk and ideas. They're quick, curious, and can juggle five ideas at once. They thrive on variety and good conversation. On a project they bring fresh angles and rapid-fire ideas, and they shine at writing and anything with words. They can scatter, but they're brilliant to brainstorm with. They click best with Libra, Aquarius, Aries, and Leo." },
  { name: "Cancer", icon: "♋", tag: "The Nurturer", short: "Intuitive, emotional, protective.", long: "Cancer is ruled by the Moon, so they're intuitive and deeply in touch with feeling. They make spaces where people feel safe and free to open up. Their emotional smarts make them amazing at work with heart, like portraiture and documentary. They remember every detail and genuinely care. They click best with Scorpio, Pisces, Taurus, and Virgo." },
  { name: "Leo", icon: "♌", tag: "The Performer", short: "Creative, generous, born to shine.", long: "Leo is ruled by the Sun, the natural performer of the zodiac. They're creative, warm, and generous with their light. They love the spotlight and bring confidence and flair to everything. They lift everyone around them and expect great work. Their pride can be a thing, but their heart is huge. They click best with Aries, Sagittarius, Gemini, and Libra." },
  { name: "Virgo", icon: "♍", tag: "The Analyst", short: "Precise, practical, detailed.", long: "Virgo is ruled by Mercury and sees the details everyone else misses. They're the perfectionists, catching the tiny flaws and fixing them. On a project they bring editorial rigor, spotless technique, and a serious work ethic. They stay humble and quietly make everything better. They can over-critique, but their craft is unmatched. They click best with Taurus, Capricorn, Cancer, and Scorpio." },
  { name: "Libra", icon: "♎", tag: "The Diplomat", short: "Balanced, social, artistic.", long: "Libra is ruled by Venus and has an eye for beauty everywhere. They've got natural taste for composition, style, and proportion. They're the peacemakers who keep a team in harmony. They shine at anything visual, like design, fashion, and art direction. They can be indecisive, but their taste is flawless. They click best with Gemini, Aquarius, Aries, and Sagittarius." },
  { name: "Scorpio", icon: "♏", tag: "The Strategist", short: "Intense, brave, transformative.", long: "Scorpio is ruled by Pluto and Mars, so they're intense and all-in. When they commit, their focus and depth are unmatched. They're drawn to the dark, the mysterious, and the real. On a project they bring raw intensity and the courage to go where others won't. They're loyal to the end and demand honesty. They click best with Cancer, Pisces, Taurus, and Capricorn." },
  { name: "Sagittarius", icon: "♐", tag: "The Explorer", short: "Adventurous, idealistic, free.", long: "Sagittarius is ruled by Jupiter, the explorer of the zodiac. They're generous, optimistic, and always chasing the next horizon. They hate being boxed in and push creative limits. They bring humor, big-picture vision, and a why-not attitude. They can lose interest in the follow-through, but their energy is magnetic. They click best with Aries, Leo, Gemini, and Libra." },
  { name: "Capricorn", icon: "♑", tag: "The Achiever", short: "Disciplined, ambitious, steady.", long: "Capricorn is ruled by Saturn, so they're disciplined and built for the long game. They make things that last and deliver on time, every time, without drama. On a project they're the reliable one who respects craft and earned success. They can be serious, but you can always count on them. They click best with Taurus, Virgo, Cancer, and Scorpio." },
  { name: "Aquarius", icon: "♒", tag: "The Visionary", short: "Original, progressive, independent.", long: "Aquarius is ruled by Uranus, the visionary of the zodiac. They think years ahead and invent new creative forms before anyone else. They champion causes, love technology, and skip convention. On a project they bring radical originality and a team-first spirit. They can seem distant, but their genius is real. They click best with Gemini, Libra, Aries, and Sagittarius." },
  { name: "Pisces", icon: "♓", tag: "The Dreamer", short: "Artistic, intuitive, boundless.", long: "Pisces is ruled by Neptune, the dreamer and mystic of the zodiac. They feel everything and turn raw emotion into beautiful art. They have no creative limits and can imagine anything. On a team they're selfless, empathetic, and tuned into the group's mood. They can struggle with boundaries, but their imagination is the soul of the project. They click best with Cancer, Scorpio, Taurus, and Virgo." },
];

export const CODEX_CHINESE: { name: string; icon: string; short: string; long: string }[] = [
  { name: "Rat", icon: "GiRat", short: "Quick-witted, resourceful.", long: "The Rat is first in the cycle and stands for smarts and adaptability. Rats are quick, resourceful, and spot opportunity everywhere. They move fast and land on their feet. On a project they're clever problem-solvers who can pivot in a snap." },
  { name: "Ox", icon: "GiBullHorns", short: "Steadfast, reliable.", long: "The Ox stands for diligence and dependability. Ox folks are steady, methodical, and incredibly hard-working. They build careers through patient, consistent effort and always deliver." },
  { name: "Tiger", icon: "GiTigerHead", short: "Courageous, magnetic.", long: "The Tiger stands for courage and charisma. Tigers are bold, competitive, and magnetic, bringing fearless energy to everything they touch. They're born leaders who inspire others to take a chance." },
  { name: "Rabbit", icon: "GiRabbit", short: "Graceful, diplomatic.", long: "The Rabbit stands for gentleness and grace. Rabbit folks are elegant and diplomatic, preferring harmony over conflict. They bring quiet excellence and refined taste to creative work." },
  { name: "Dragon", icon: "GiDragonHead", short: "Charismatic, ambitious.", long: "The Dragon is the most powerful sign, standing for luck and ambition. Dragons are charismatic, confident, and built for big things. They lead with flair and pull everyone along with their drive." },
  { name: "Snake", icon: "GiSnake", short: "Wise, intuitive.", long: "The Snake stands for wisdom and intuition. Snake folks are deep thinkers who move with careful precision. They're philosophical and see beneath the surface, adding strategic depth to any project." },
  { name: "Horse", icon: "GiHorseHead", short: "Energetic, independent.", long: "The Horse stands for freedom and energy. Horse folks are spirited and independent, always chasing adventure. Their enthusiasm and speed make them exciting, if restless, collaborators." },
  { name: "Goat", icon: "GiGoat", short: "Creative, gentle.", long: "The Goat (or Sheep) stands for peace and creativity. Goat folks are gentle, artistic, and nurturing, creating beauty and calm wherever they go. They're wonderful at emotional, human-centered work." },
  { name: "Monkey", icon: "GiMonkey", short: "Clever, inventive.", long: "The Monkey stands for wit and invention. Monkey folks are clever, playful, and endlessly inventive, finding unexpected solutions and keeping things fun." },
  { name: "Rooster", icon: "GiRooster", short: "Confident, exacting.", long: "The Rooster stands for confidence and precision. Rooster folks are observant, exacting, and proud of their craft. They're detail-obsessed and bring polish and punctuality to every project." },
  { name: "Dog", icon: "GiSittingDog", short: "Loyal, honest.", long: "The Dog stands for loyalty and integrity. Dog folks are honest, protective, and fiercely loyal, the collaborator you can always count on. They bring trust and warmth to any team." },
  { name: "Pig", icon: "GiPig", short: "Generous, sincere.", long: "The Pig stands for generosity and sincerity. Pig folks are warm, genuine, and whole-hearted, bringing authenticity and abundance to everything they do. Their kindness makes them easy to love working with." },
];

export const CODEX_LIFE_PATH: { n: number; title: string; long: string }[] = [
  { n: 1, title: "The Leader", long: "Life Path 1 is the pioneer, independent and ambitious, a born starter. Ones are here to lead, create, and break new ground. They hate being micromanaged and do their best with freedom. On a project they're the ones who launch things and set the direction. Their challenge is learning to collaborate without taking over." },
  { n: 2, title: "The Diplomat", long: "Life Path 2 is the peacemaker, sensitive, cooperative, and deeply intuitive. Twos are the glue of any collaboration, sensing the mood and keeping things harmonious. They shine at partnership and anything that needs tact. Their challenge is setting boundaries and not losing themselves in others." },
  { n: 3, title: "The Creative", long: "Life Path 3 is the expressive artist, joyful and born to create. Threes are the natural writers, performers, and visual artists. They process the world through expression and bring lightness and humor. Their challenge is staying focused and finishing what they start." },
  { n: 4, title: "The Builder", long: "Life Path 4 is the master builder, disciplined and reliable. Fours turn vision into solid, lasting work through patience and good systems. They're the ones who make ideas real. Their challenge is loosening up and trusting the unknown." },
  { n: 5, title: "The Freedom Seeker", long: "Life Path 5 is the adventurer, versatile and restless. Fives thrive on variety, travel, and bold experiments. They bring energy and adaptability to every project. Their challenge is commitment and following through." },
  { n: 6, title: "The Nurturer", long: "Life Path 6 is the caregiver, responsible and loving. Sixes make collaborators feel supported, safe, and valued. They bring warmth and a strong sense of duty to every team. Their challenge is over-giving and perfectionism." },
  { n: 7, title: "The Seeker", long: "Life Path 7 is the mystic, analytical and introspective. Sevens dig beneath the surface and bring depth and wisdom to creative work. They shine at concept and meaning. Their challenge is staying connected to the outside world." },
  { n: 8, title: "The Powerhouse", long: "Life Path 8 is the executive, driven and commanding. Eights turn ambition into real success and understand power and money. They're natural producers and leaders. Their challenge is balancing success with heart." },
  { n: 9, title: "The Humanitarian", long: "Life Path 9 is the visionary, compassionate and wise. Nines make work that serves a bigger purpose and inspires change. They bring idealism and empathy to everything. Their challenge is letting go and finishing cycles." },
  { n: 11, title: "The Illuminator (Master Number)", long: "Life Path 11 is a Master Number, intensely intuitive and inspired, a channel for big ideas. Elevens bring spiritual depth and flashes of genius. Their challenge is grounding their gifts and managing their sensitivity." },
  { n: 22, title: "The Master Builder (Master Number)", long: "Life Path 22 is the most powerful number, the Master Builder who dreams on a huge scale and has the discipline to actually build it. Twenty-twos blend vision with execution to leave a real legacy. Their challenge is the sheer weight of their own potential." },
  { n: 33, title: "The Master Teacher (Master Number)", long: "Life Path 33 is the rarest Master Number, the Master Teacher who lifts up everyone around them. Thirty-threes live and breathe kindness and service. Their challenge is remembering to care for themselves too." },
];

export const CODEX_MBTI: { code: string; tag: string; short: string; long: string; best: string }[] = [
  { code: "INTJ", tag: "The Architect", short: "Strategic, independent, future-focused.", long: "INTJs are rare, visionary planners. They see patterns others miss and build airtight long-term plans. They're independent and analytical, happiest solo but strong leaders when needed. On a project they're the master planners and concept architects. They can seem reserved but they're deeply loyal. They click best with ENTP and ENFP.", best: "ENTP, ENFP" },
  { code: "INTP", tag: "The Logician", short: "Inventive, analytical, curious.", long: "INTPs are the theorists, endlessly curious and precise. They take ideas apart to the studs and rebuild them better. They love a good intellectual puzzle and bring fresh concepts to creative work. They click best with ENTJ and ENFJ.", best: "ENTJ, ENFJ" },
  { code: "ENTJ", tag: "The Commander", short: "Bold, decisive, a leader.", long: "ENTJs are born leaders, bold and decisive. They rally teams, set big goals, and push projects to the finish on schedule. On a project they're the directors and producers who make it happen. They click best with INTP and INFP.", best: "INTP, INFP" },
  { code: "ENTP", tag: "The Debater", short: "Witty, inventive, idea-generator.", long: "ENTPs are quick-witted idea machines who love a good challenge. They spark innovation through debate and exploration and see possibilities everywhere. They bring energy and offbeat brilliance to everything. They click best with INTJ and INFJ.", best: "INTJ, INFJ" },
  { code: "INFJ", tag: "The Advocate", short: "Visionary, principled, quiet.", long: "INFJs are quiet visionaries with strong principles. They craft deep meaning and chase causes with quiet fire. Their rare mix of insight and empathy makes them transformative collaborators. They click best with ENFP and ENTP.", best: "ENFP, ENTP" },
  { code: "INFP", tag: "The Mediator", short: "Idealistic, creative, authentic.", long: "INFPs are idealistic creatives driven by their values. They turn emotion and imagination into deeply original work. Gentle but principled, they bring soul and integrity to every team. They click best with ENFJ and ENTJ.", best: "ENFJ, ENTJ" },
  { code: "ENFJ", tag: "The Protagonist", short: "Charismatic, empathetic leader.", long: "ENFJs are charismatic, big-hearted leaders who bring out the best in people. They make collaborators feel seen and valued. Natural mentors and motivators, they shine at creative direction. They click best with INFP and INTP.", best: "INFP, INTP" },
  { code: "ENFP", tag: "The Campaigner", short: "Enthusiastic, spontaneous, social.", long: "ENFPs are enthusiastic free spirits who light up any room. They're creative chameleons, full of warmth and new ideas. Their energy and empathy make them magnetic to work with. They click best with INFJ and INTJ.", best: "INFJ, INTJ" },
  { code: "ISTJ", tag: "The Logistician", short: "Dependable, detailed, organized.", long: "ISTJs are dependable, detail-driven, and deeply organized. They deliver flawless work and keep every promise. On a project they're the rock-solid backbone of the production. They click best with ESFP and ESTP.", best: "ESFP, ESTP" },
  { code: "ISFJ", tag: "The Defender", short: "Warm, meticulous, protective.", long: "ISFJs are warm, careful, and quietly protective. They're the reliable core of any crew, conscientious and detail-driven. They bring stability and heart to every project. They click best with ESFP and ESTP.", best: "ESFP, ESTP" },
  { code: "ESTJ", tag: "The Executive", short: "Efficient, organized, decisive.", long: "ESTJs are efficient organizers who turn plans into reality. They run tight, productive productions with clear systems and high standards. Their leadership and reliability are gold on set. They click best with ISFP and ISTP.", best: "ISFP, ISTP" },
  { code: "ESFJ", tag: "The Consul", short: "Harmonious, people-first.", long: "ESFJs are warm, people-first collaborators who keep teams connected and morale high. They're conscientious and great at coordination. They shine at client relations and team culture. They click best with ISFP and ISTP.", best: "ISFP, ISTP" },
  { code: "ISTP", tag: "The Virtuoso", short: "Hands-on, calm, a tinkerer.", long: "ISTPs are hands-on tinkerers, cool under pressure and great with tools. They solve problems on the fly with calm precision. On a project they're the technical wizards. They click best with ESFJ and ESTJ.", best: "ESFJ, ESTJ" },
  { code: "ISFP", tag: "The Adventurer", short: "Artistic, spontaneous, sensory.", long: "ISFPs are artistic adventurers who live by what looks and feels right. They create beauty in the moment and have a natural eye for craft. Quiet but expressive, they bring authenticity to every frame. They click best with ESFJ and ESTJ.", best: "ESFJ, ESTJ" },
  { code: "ESTP", tag: "The Entrepreneur", short: "Bold, energetic, pragmatic.", long: "ESTPs are bold, energetic pragmatists who love being on set. They make fast decisions with style and handle chaos like a pro. Their charisma and hands-on energy make them great to work with. They click best with ISTJ and ISFJ.", best: "ISTJ, ISFJ" },
  { code: "ESFP", tag: "The Entertainer", short: "Lively, expressive, magnetic.", long: "ESFPs are lively performers who bring the show, and the crowd. They're magnetic, spontaneous, and tuned into the moment. They shine at performance and anything high-energy. They click best with ISTJ and ISFJ.", best: "ISTJ, ISFJ" },
];

export const CODEX_TYPES: { name: string; icon: string; long: string }[] = [
  { name: "Photographer", icon: "📷", long: "Captures still images across editorial, portrait, fashion, fine art, and commercial work. Photographers master light, composition, and the camera to freeze moments into art." },
  { name: "Model", icon: "🧍", long: "The person in front of the camera, for runway, editorial, figure, and lifestyle work. Models bring creative ideas to life with presence, poise, and expression." },
  { name: "Content Creator", icon: "🎥", long: "Makes social and digital content for brands and audiences. Content creators blend storytelling, editing, and platform know-how to build a real following." },
  { name: "Director", icon: "🎬", long: "Leads the creative vision on set for film, music videos, commercials, and experimental work. Directors pull cast, crew, and concept together into one finished piece." },
  { name: "Editor", icon: "✂️", long: "The post-production craft of cutting, pacing, color, effects, and finishing. Editors turn raw footage into story, rhythm, and feeling." },
  { name: "MUA", icon: "💄", long: "A makeup artist who turns faces and bodies into art. MUAs design looks for editorial, beauty, film, and special effects with a deep sense of color and shape." },
  { name: "Stylist", icon: "👗", long: "Curates the wardrobe, props, and overall look of a shoot. Stylists translate a concept into a visual language through fashion and detail." },
  { name: "Actor", icon: "🎭", long: "Performs characters across film, stage, and commercials. Actors bring scripts to life with craft, emotion, and vulnerability." },
  { name: "Videographer", icon: "📹", long: "Captures moving images with drone, gimbal, documentary, and event work. Videographers master motion, stability, and telling stories in real time." },
  { name: "Writer", icon: "✍️", long: "Crafts narrative with scripts, copy, essays, and editorial prose. Writers turn ideas into words that move, persuade, and stick." },
  { name: "Producer", icon: "📋", long: "Makes it all happen with funding, crew, schedule, and logistics. Producers turn a creative vision into a real, finished, deliverable project." },
  { name: "Designer", icon: "🎨", long: "Shapes visual systems like branding, UI/UX, layout, and identity. Designers solve problems with typography, color, and form." },
];

export const CODEX_AESTHETICS: { name: string; long: string }[] = [
  { name: "Portrait", long: "Focused on the person, their face, form, and expression. Portraiture is about revealing character, mood, and identity." },
  { name: "Editorial", long: "Magazine-style storytelling images with a narrative thread. Editorial work tells stories through a sequence of styled photos." },
  { name: "Commercial", long: "Brand and advertising work built to sell a product or idea. Commercial images put clarity and appeal first." },
  { name: "Music Video", long: "Moving images synced to music, performance, and rhythm. Music videos blend cinematography and sound for a full-body feel." },
  { name: "Documentary", long: "Real, unscripted storytelling, the truth caught on camera. Documentary work shows things as they really are." },
  { name: "Branding", long: "Visual identity, logos, and cohesive brand systems. Branding builds recognition and meaning through consistent design." },
  { name: "Body Art", long: "Fine-art figure and body-paint photography of the human form. Body art celebrates the body as both canvas and sculpture." },
  { name: "Fine Art", long: "Gallery-minded imagery that puts concept and emotion ahead of commerce. Fine art is personal, expressive, and unafraid." },
  { name: "Fashion", long: "Work centered on clothing, style, and the runway. Fashion photography and film celebrate design, movement, and culture." },
  { name: "Experimental", long: "Unconventional, boundary-pushing approaches to image and film. Experimental work reinvents the medium itself." },
  { name: "Dark", long: "Moody, dramatic, low-key visuals with strong contrast. Dark work explores shadow, tension, and atmosphere." },
  { name: "Dreamy", long: "Soft, ethereal, romantic visuals with hazy light. Dreamy work leans into nostalgia, fantasy, and softness." },
  { name: "Bold", long: "High-impact, saturated, unapologetically striking images. Bold work grabs attention with color and confidence." },
  { name: "Vintage", long: "Retro, film-inspired visuals with a warm, nostalgic feel. Vintage work channels the look of earlier eras." },
  { name: "Abstract", long: "Art that isn't tied to a subject, focused on form, color, and texture. Abstract work puts feeling before subject." },
  { name: "Film", long: "Moving-picture work like narrative, short, and feature film. Film is the fullest expression of visual storytelling." },
];
