export type Profile = typeof PROFILES[number] & { photos?: string[]; badges?: {name:string;desc:string;icon:string;color:string}[]; matchScore?: number; rulesScore?: number; cosineScore?: number };
export type Brief = typeof BRIEFS[number];
export type Match = Partial<Profile> & {
  id: number; name: string; img: string; type: string;
  bio?: string; location?: string; distanceMi?: number; booked?: boolean;
  intent?: string;
  messages: { from: string; text: string; time: string; img?: string }[];
};
export type Screen = "auth"|"onboard"|"discover"|"connections"|"matches"|"chat"|"profile"|"briefs"|"portfolio"|"settings"|"subscription"|"community"|"events"|"sessions"|"moments"|"forum"|"network";

export const EXCLUDED_PORTFOLIOS = [
  "/models/NIK/",
  "/models/Nik/",
  "/models/nik/",
];

export const PROFILES = [
  { id:1,name:"ARCANA",type:"Photographer",img:"/models/ARCANA/Bodypaint-2.webp",loc:"Los Angeles, CA",bio:"Golden hour chaser. Capturing raw emotion through natural light.",collabs:47,score:77,verified:true,styles:["Editorial", "Fine Art", "Fashion"],looking:["Videographer", "Editor"],connection:"collab",nsfw:false,online:true,zodiac:"Sagittarius",chinese:"Rooster",mbti:"INTJ",lifePath:9,badges:[{name: "Verified Pro", desc: "Identity verified by Muse", icon: "\u2713", color: "#FFD700"}, {name: "Top Creator", desc: "80+ collaborations completed", icon: "\u2605", color: "#FF8A80"}],prompts:[{q:"My creative superpower is",a:"Finding beauty in the chaos of golden hour — every shoot feels like a race against the sun"},{q:"The project I'm most proud of",a:"A 40-page editorial for Vogue Italia shot entirely on 35mm film"}],prompts:[{q:"My creative superpower is",a:"Finding beauty in the chaos of golden hour — every shoot feels like a race against the sun"},{q:"The project I'm most proud of",a:"A 40-page editorial for Vogue Italia shot entirely on 35mm film"}],albums:[{title:"Editorial",photos:["/models/ARCANA/Bodypaint-2.webp","/models/ARCANA/Bodypaint-3.webp","/models/ARCANA/Bodypaint-5.webp"]},{title:"Fine Art",photos:["/models/ARCANA/Bodypaint.webp","/models/ARCANA/Bodypaint-10.webp","/models/ARCANA/Bodypaint-4.webp"]},{title:"Fashion",photos:["/models/ARCANA/Bodypaint-15.webp","/models/ARCANA/Bodypaint-8.webp","/models/ARCANA/Bodypaint-7.webp"]}],photos:["/models/ARCANA/Bodypaint-2.webp", "/models/ARCANA/Bodypaint-3.webp", "/models/ARCANA/Bodypaint-5.webp", "/models/ARCANA/Bodypaint.webp", "/models/ARCANA/Bodypaint-10.webp", "/models/ARCANA/Bodypaint-4.webp", "/models/ARCANA/Bodypaint-15.webp", "/models/ARCANA/Bodypaint-8.webp", "/models/ARCANA/Bodypaint-7.webp", "/models/ARCANA/Bodypaint-11.webp"] },
  { id:2,name:"AUDREY",type:"Director",img:"/models/AUDREY/Audrey-20.webp",loc:"San Francisco, CA",bio:"Visual storyteller. Currently working on a cyberpunk noir series.",collabs:82,score:90,verified:true,styles:["Music Video", "Commercial", "Experimental"],looking:["Photographer", "Director"],connection:"friend",nsfw:false,online:false,zodiac:"Libra",chinese:"Ox",mbti:"ESFJ",lifePath:6,badges:[{name: "Verified Pro", desc: "Identity verified by Muse", icon: "\u2713", color: "#FFD700"}, {name: "Style Icon", desc: "Recognized for outstanding style", icon: "\u2726", color: "#D4A5FF"}, {name: "Creative Sage", desc: "47+ collaborations completed", icon: "\u2b21", color: "#FFB5C2"}],prompts:[{q:"I geek out on",a:"Cyberpunk aesthetics and neon lighting — Blade Runner 2049 is my bible"},{q:"Best travel tip",a:"Always pack a 50mm prime lens. Never check your camera gear."}],photos:["/models/AUDREY/Audrey-20.webp", "/models/AUDREY/Audrey-21.webp", "/models/AUDREY/Audrey-18.webp", "/models/AUDREY/Audrey-17.webp", "/models/AUDREY/Audrey-16.webp", "/models/AUDREY/Audrey-10.webp", "/models/AUDREY/Audrey-19.webp", "/models/AUDREY/Audrey-2.webp", "/models/AUDREY/Audrey-1.webp", "/models/AUDREY/Audrey-1-3.webp"] },
  { id:3,name:"CHER",type:"Musician",img:"/models/CHER/CHER-370.webp",loc:"Nashville, TN",bio:"Multi-instrumentalist. Looking to score visual projects.",collabs:23,score:81,verified:false,styles:["Commercial", "Experimental"],looking:["Videographer", "Editor"],connection:"partner",nsfw:false,online:true,zodiac:"Libra",chinese:"Dragon",mbti:"ENFP",lifePath:22,badges:[{name: "Super Collab", desc: "High match compatibility", icon: "\u2661", color: "#FF69B4"}, {name: "Style Icon", desc: "Recognized for outstanding style", icon: "\u2726", color: "#D4A5FF"}, {name: "Match Magnet", desc: "10+ matches this month", icon: "\u2661", color: "#FF69B4"}, {name: "Quick Responder", desc: "Responds within 2 hours", icon: "\u26a1", color: "#FFD700"}],prompts:[{q:"My most controversial opinion",a:"Digital music lacks the warmth of analog tape — fight me"},{q:"Two truths and a lie",a:"I play 7 instruments. I have never performed live. I write songs in my sleep."}],photos:["/models/CHER/CHER-370.webp", "/models/CHER/CHER-220.webp", "/models/CHER/CHER-334.webp", "/models/CHER/CHER-357.webp", "/models/CHER/CHER-333.webp", "/models/CHER/CHER-111.webp", "/models/CHER/CHER-323.webp", "/models/CHER/CHER-225.webp", "/models/CHER/CHER-223.webp", "/models/CHER/CHER-187.webp"] },
  { id:4,name:"CHHAVI",type:"Photographer",img:"/models/CHHAVI/Chhavi-9.webp",loc:"Miami, FL",bio:"Boudoir and fine art photographer. Light and shadow play.",collabs:56,score:79,verified:true,styles:["Fine Art", "Portrait", "Body Art"],looking:["Videographer", "Editor"],connection:"partner",nsfw:false,online:false,zodiac:"Libra",chinese:"Dog",mbti:"ESTP",lifePath:3,badges:[{name: "Verified Pro", desc: "Identity verified by Muse", icon: "\u2713", color: "#FFD700"}, {name: "Match Magnet", desc: "10+ matches this month", icon: "\u2661", color: "#FF69B4"}],prompts:[{q:"My photography mantra",a:"Every body tells a story — I just help write the chapter"},{q:"Unpopular opinion",a:"Boudoir photography is not about sensuality, it is about self-discovery"}],photos:["/models/CHHAVI/Chhavi-9.webp", "/models/CHHAVI/Chhavi-8.webp", "/models/CHHAVI/Chhavi-13.webp", "/models/CHHAVI/Chhavi-5.webp", "/models/CHHAVI/Chhavi-3.webp", "/models/CHHAVI/Chhavi-6.webp", "/models/CHHAVI/Chhavi.webp", "/models/CHHAVI/Chhavi-4.webp", "/models/CHHAVI/Chhavi-10.webp", "/models/CHHAVI/Chhavi-7.webp"] },
  { id:5,name:"CLAIRE",type:"Videographer",img:"/models/CLAIRE/Claire-10.webp",loc:"Denver, CO",bio:"Drone cinematography and landscape films.",collabs:18,score:84,verified:false,styles:["Commercial", "Documentary"],looking:["Photographer", "Director"],connection:"friend",nsfw:false,online:false,zodiac:"Taurus",chinese:"Tiger",mbti:"INFP",lifePath:22,badges:[{name: "Rising Star", desc: "New to Muse, gaining traction", icon: "\u2726", color: "#98FB98"}, {name: "Quick Responder", desc: "Responds within 2 hours", icon: "\u26a1", color: "#FFD700"}, {name: "Match Magnet", desc: "10+ matches this month", icon: "\u2661", color: "#FF69B4"}, {name: "Style Icon", desc: "Recognized for outstanding style", icon: "\u2726", color: "#D4A5FF"}],prompts:[{q:"I am convinced that",a:"The best drone shots happen when you throw the flight plan away and follow the light"},{q:"What I am looking for",a:"A creative partner who is not afraid of 5am call times for the perfect sunrise"}],photos:["/models/CLAIRE/Claire-10.webp", "/models/CLAIRE/Claire-121.webp", "/models/CLAIRE/Claire-112.webp", "/models/CLAIRE/Claire-12.webp", "/models/CLAIRE/Claire-111.webp", "/models/CLAIRE/Claire-101.webp", "/models/CLAIRE/Claire-103.webp", "/models/CLAIRE/Claire-100.webp", "/models/CLAIRE/Claire-109.webp", "/models/CLAIRE/Claire-110.webp"] },
  { id:6,name:"DEKETRA",type:"Director",img:"/models/DEKETRA/Dee-110.webp",loc:"Portland, OR",bio:"Queer filmmaker crafting authentic narratives.",collabs:64,score:85,verified:true,styles:["Editorial", "Music Video", "Experimental"],looking:["Photographer", "Director", "Editor"],connection:"mentor",nsfw:false,online:false,zodiac:"Taurus",chinese:"Dragon",mbti:"ISFP",lifePath:3,badges:[{name: "Verified Pro", desc: "Identity verified by Muse", icon: "\u2713", color: "#FFD700"}, {name: "Creative Sage", desc: "47+ collaborations completed", icon: "\u2b21", color: "#FFB5C2"}, {name: "Rising Star", desc: "New to Muse, gaining traction", icon: "\u2726", color: "#98FB98"}, {name: "Quick Responder", desc: "Responds within 2 hours", icon: "\u26a1", color: "#FFD700"}],prompts:[{q:"The story I was born to tell",a:"Queer joy in cinema — not trauma, not tragedy, just beautiful authentic lives"},{q:"My filmmaking hero",a:"Hayao Miyazaki. Every frame a painting, every story a meditation"}],photos:["/models/DEKETRA/Dee-110.webp", "/models/DEKETRA/Dee-101.webp", "/models/DEKETRA/Dee-113.webp", "/models/DEKETRA/Dee-108.webp", "/models/DEKETRA/Dee-114.webp", "/models/DEKETRA/Dee-100.webp", "/models/DEKETRA/Dee-102.webp", "/models/DEKETRA/Dee-116.webp", "/models/DEKETRA/Dee-104.webp", "/models/DEKETRA/Dee-117.webp"] },
  { id:7,name:"EBONIE",type:"Editor",img:"/models/EBONIE/Ebonie-335.webp",loc:"Seattle, WA",bio:"Post-production specialist. VFX and color.",collabs:39,score:81,verified:true,styles:["Fashion", "Commercial", "Branding"],looking:["Videographer", "Editor"],connection:"mentor",nsfw:false,online:true,zodiac:"Gemini",chinese:"Monkey",mbti:"INTJ",lifePath:11,badges:[{name: "Verified Pro", desc: "Identity verified by Muse", icon: "\u2713", color: "#FFD700"}, {name: "Quick Responder", desc: "Responds within 2 hours", icon: "\u26a1", color: "#FFD700"}, {name: "Local Legend", desc: "Top creative in their city", icon: "\ud83d\udccd", color: "#87CEEB"}, {name: "Rising Star", desc: "New to Muse, gaining traction", icon: "\u2726", color: "#98FB98"}],prompts:[{q:"My editing philosophy",a:"Every frame is a canvas — I just remove what doesn't belong"},{q:"Most satisfying moment",a:"When the director sees the first rough cut and says nothing for 30 seconds — that silence is gold"}],photos:["/models/EBONIE/Ebonie-335.webp", "/models/EBONIE/Ebonie-329.webp", "/models/EBONIE/Ebonie-332.webp", "/models/EBONIE/Ebonie-336.webp", "/models/EBONIE/Ebonie-340.webp", "/models/EBONIE/Ebonie-344.webp", "/models/EBONIE/Ebonie-338.webp", "/models/EBONIE/Ebonie-341.webp", "/models/EBONIE/Ebonie-337.webp", "/models/EBONIE/Ebonie-342.webp"] },
  { id:8,name:"FARREN_BODYPAINT",type:"Photographer",img:"/models/FARREN_BODYPAINT/Bodypaint-102.webp",loc:"Chicago, IL",bio:"Street photography and urban exploration.",collabs:15,score:90,verified:false,styles:["Documentary", "Experimental", "Portrait"],looking:["Videographer", "Editor"],connection:"partner",nsfw:false,online:true,zodiac:"Sagittarius",chinese:"Tiger",mbti:"ISTJ",lifePath:9,badges:[{name: "Style Icon", desc: "Recognized for outstanding style", icon: "\u2726", color: "#D4A5FF"}, {name: "Super Collab", desc: "High match compatibility", icon: "\u2661", color: "#FF69B4"}, {name: "Rising Star", desc: "New to Muse, gaining traction", icon: "\u2726", color: "#98FB98"}, {name: "Local Legend", desc: "Top creative in their city", icon: "\ud83d\udccd", color: "#87CEEB"}],prompts:[{q:"Body art is",a:"Not just paint on skin — it is identity made visible, one brushstroke at a time"},{q:"My dream collaboration",a:"A full-body paint series exploring the 4 elements with a symphony orchestra scoring the shoot"}],photos:["/models/FARREN_BODYPAINT/Bodypaint-102.webp", "/models/FARREN_BODYPAINT/Bodypaint-103.webp", "/models/FARREN_BODYPAINT/Bodypaint-101.webp", "/models/FARREN_BODYPAINT/Bodypaint-10.webp", "/models/FARREN_BODYPAINT/Bodypaint-107.webp", "/models/FARREN_BODYPAINT/Bodypaint-100.webp", "/models/FARREN_BODYPAINT/Bodypaint-106.webp", "/models/FARREN_BODYPAINT/Bodypaint-104.webp", "/models/FARREN_BODYPAINT/Bodypaint-105.webp", "/models/FARREN_BODYPAINT/Bodypaint-11.webp"] },
  { id:10,name:"FLUFFY",type:"Director",img:"/models/FLUFFY/FLUFFY-22.webp",loc:"New York, NY",bio:"Commercial and music video director.",collabs:73,score:78,verified:true,styles:["Music Video", "Commercial", "Fashion"],looking:["Photographer", "Director"],connection:"mentor",nsfw:false,online:true,zodiac:"Aries",chinese:"Rooster",mbti:"ENFP",lifePath:11,badges:[{name: "Verified Pro", desc: "Identity verified by Muse", icon: "\u2713", color: "#FFD700"}, {name: "Super Collab", desc: "High match compatibility", icon: "\u2661", color: "#FF69B4"}, {name: "Top Creator", desc: "80+ collaborations completed", icon: "\u2605", color: "#FF8A80"}, {name: "Creative Sage", desc: "47+ collaborations completed", icon: "\u2b21", color: "#FFB5C2"}],prompts:[{q:"Commercial directing secret",a:"The best ads feel like they are not ads — they feel like the life you want"},{q:"My creative process",a:"I storyboard every single frame. Then on set I throw half of it away and follow the energy"}],photos:["/models/FLUFFY/FLUFFY-22.webp", "/models/FLUFFY/FLUFFY-15.webp", "/models/FLUFFY/FLUFFY-17.webp", "/models/FLUFFY/FLUFFY-10.webp", "/models/FLUFFY/FLUFFY-12.webp", "/models/FLUFFY/FLUFFY-2.webp", "/models/FLUFFY/FLUFFY-11.webp", "/models/FLUFFY/FLUFFY-14.webp", "/models/FLUFFY/FLUFFY-21.webp"] },
  { id:11,name:"J.RED",type:"Musician",img:"/models/J.RED/J.Red-9.webp",loc:"Los Angeles, CA",bio:"Electronic music producer. Synthwave vibes.",collabs:12,score:89,verified:true,styles:["Experimental", "Commercial"],looking:["Director", "Photographer"],connection:"partner",nsfw:false,online:true,zodiac:"Cancer",chinese:"Monkey",mbti:"INFJ",lifePath:33,badges:[{name: "Verified Pro", desc: "Identity verified by Muse", icon: "\u2713", color: "#FFD700"}, {name: "Creative Sage", desc: "47+ collaborations completed", icon: "\u2b21", color: "#FFB5C2"}, {name: "Quick Responder", desc: "Responds within 2 hours", icon: "\u26a1", color: "#FFD700"}],prompts:[{q:"My sound in 3 words",a:"Ambient. Textured. Cinematic."},{q:"The gig that changed me",a:"Opening for a silent film screening at an abandoned theater — the acoustics were haunting"}],photos:["/models/J.RED/J.Red-9.webp", "/models/J.RED/J.Red-2.webp", "/models/J.RED/J.Red.webp", "/models/J.RED/J.Red-14.webp", "/models/J.RED/J.Red-3.webp", "/models/J.RED/J.Red-4.webp", "/models/J.RED/J.Red-11.webp", "/models/J.RED/J.Red-12.webp", "/models/J.RED/J.Red-6.webp"] },
  { id:13,name:"JEREMY",type:"Photographer",img:"/models/JEREMY/JEREMY-9.webp",loc:"Las Vegas, NV",bio:"Fine art figure photographer. The body as living canvas.",collabs:94,score:95,verified:true,styles:["Body Art", "Fine Art", "Fashion"],looking:["Director", "Editor"],connection:"friend",nsfw:true,online:true,zodiac:"Aries",chinese:"Dog",mbti:"INTJ",lifePath:2,badges:[{name: "Verified Pro", desc: "Identity verified by Muse", icon: "\u2713", color: "#FFD700"}, {name: "Super Collab", desc: "High match compatibility", icon: "\u2661", color: "#FF69B4"}, {name: "Creative Sage", desc: "47+ collaborations completed", icon: "\u2b21", color: "#FFB5C2"}],photos:["/models/JEREMY/JEREMY-9.webp", "/models/JEREMY/JEREMY-7.webp", "/models/JEREMY/JEREMY-13.webp", "/models/JEREMY/JEREMY-15.webp", "/models/JEREMY/JEREMY-3.webp", "/models/JEREMY/JEREMY-8.webp", "/models/JEREMY/JEREMY-4.webp", "/models/JEREMY/JEREMY-14.webp", "/models/JEREMY/JEREMY-2.webp"] },
  { id:15,name:"MARISSA",type:"Director",img:"/models/MARISSA/Marissa-14.webp",loc:"Miami, FL",bio:"Fine art director pushing boundaries through light.",collabs:112,score:73,verified:true,styles:["Body Art", "Experimental", "Commercial"],looking:["Photographer", "Videographer"],connection:"collab",nsfw:true,online:false,zodiac:"Aries",chinese:"Monkey",mbti:"ENTJ",lifePath:3,badges:[{name: "Verified Pro", desc: "Identity verified by Muse", icon: "\u2713", color: "#FFD700"}, {name: "Top Creator", desc: "80+ collaborations completed", icon: "\u2605", color: "#FF8A80"}],photos:["/models/MARISSA/Marissa-14.webp", "/models/MARISSA/Marissa-15.webp", "/models/MARISSA/Marissa-6.webp", "/models/MARISSA/Marissa-16.webp", "/models/MARISSA/Marissa-5.webp", "/models/MARISSA/Marissa-7.webp", "/models/MARISSA/Marissa-3.webp", "/models/MARISSA/Marissa.webp", "/models/MARISSA/Marissa-4.webp", "/models/MARISSA/Marissa-18.webp"] },
  { id:16,name:"MARSHAWNA",type:"Editor",img:"/models/MARSHAWNA/Marshawna-5.webp",loc:"New York, NY",bio:"Post-production for fine art figure and fashion.",collabs:37,score:92,verified:false,styles:["Body Art", "Fashion", "Editorial"],looking:["Videographer", "Editor"],connection:"mentor",nsfw:true,online:false,zodiac:"Cancer",chinese:"Dragon",mbti:"ISTP",lifePath:3,badges:[{name: "Super Collab", desc: "High match compatibility", icon: "\u2661", color: "#FF69B4"}, {name: "Local Legend", desc: "Top creative in their city", icon: "\ud83d\udccd", color: "#87CEEB"}, {name: "Quick Responder", desc: "Responds within 2 hours", icon: "\u26a1", color: "#FFD700"}],photos:["/models/MARSHAWNA/Marshawna-5.webp", "/models/MARSHAWNA/Marshawna-2.webp", "/models/MARSHAWNA/Marshawna-7.webp", "/models/MARSHAWNA/Marshawna-3.webp", "/models/MARSHAWNA/Marshawna-8.webp", "/models/MARSHAWNA/Marshawna-14.webp", "/models/MARSHAWNA/Marshawna-15.webp", "/models/MARSHAWNA/Marshawna-13.webp", "/models/MARSHAWNA/Marshawna-6.webp"] },
  { id:17,name:"MITRI",type:"Photographer",img:"/models/MITRI/Mitri-103.webp",loc:"San Francisco, CA",bio:"Lifestyle and portrait photographer for the bold.",collabs:44,score:85,verified:true,styles:["Portrait", "Editorial", "Branding"],looking:["Director", "Photographer"],connection:"friend",nsfw:false,online:true,zodiac:"Cancer",chinese:"Snake",mbti:"ISFJ",lifePath:3,badges:[{name: "Verified Pro", desc: "Identity verified by Muse", icon: "\u2713", color: "#FFD700"}, {name: "Match Magnet", desc: "10+ matches this month", icon: "\u2661", color: "#FF69B4"}, {name: "Quick Responder", desc: "Responds within 2 hours", icon: "\u26a1", color: "#FFD700"}, {name: "Style Icon", desc: "Recognized for outstanding style", icon: "\u2726", color: "#D4A5FF"}],photos:["/models/MITRI/Mitri-103.webp", "/models/MITRI/Mitri-100.webp", "/models/MITRI/Mitri-102.webp", "/models/MITRI/Mitri-101.webp", "/models/MITRI/Mitri-117.webp", "/models/MITRI/Mitri-10.webp", "/models/MITRI/Mitri-104.webp", "/models/MITRI/Mitri-11.webp", "/models/MITRI/Mitri-107.webp", "/models/MITRI/Mitri-110.webp"] },
  { id:18,name:"NAKIA",type:"Videographer",img:"/models/NAKIA/Nakia-100.webp",loc:"Austin, TX",bio:"Music video and short film DP.",collabs:19,score:92,verified:false,styles:["Music Video", "Documentary", "Experimental"],looking:["Director", "Photographer"],connection:"mentor",nsfw:false,online:true,zodiac:"Capricorn",chinese:"Rabbit",mbti:"ESTJ",lifePath:4,badges:[{name: "Style Icon", desc: "Recognized for outstanding style", icon: "\u2726", color: "#D4A5FF"}, {name: "Local Legend", desc: "Top creative in their city", icon: "\ud83d\udccd", color: "#87CEEB"}],photos:["/models/NAKIA/Nakia-100.webp", "/models/NAKIA/Nakia-117.webp", "/models/NAKIA/Nakia-102.webp", "/models/NAKIA/Nakia-101.webp", "/models/NAKIA/Nakia-115.webp", "/models/NAKIA/Nakia-114.webp", "/models/NAKIA/Nakia-10.webp", "/models/NAKIA/Nakia-109.webp", "/models/NAKIA/Nakia-111.webp", "/models/NAKIA/Nakia-106.webp"] },
  { id:19,name:"PEYTON",type:"Model",img:"/models/PEYTON/Peyton-12.webp",loc:"Miami, FL",bio:"Runway and editorial model with a creative eye.",collabs:52,score:78,verified:true,styles:["Fashion", "Editorial", "Body Art"],looking:["Director", "Photographer"],connection:"mentor",nsfw:false,online:true,zodiac:"Aries",chinese:"Snake",mbti:"ENFJ",lifePath:22,badges:[{name: "Verified Pro", desc: "Identity verified by Muse", icon: "\u2713", color: "#FFD700"}, {name: "Style Icon", desc: "Recognized for outstanding style", icon: "\u2726", color: "#D4A5FF"}, {name: "Match Magnet", desc: "10+ matches this month", icon: "\u2661", color: "#FF69B4"}, {name: "Creative Sage", desc: "47+ collaborations completed", icon: "\u2b21", color: "#FFB5C2"}],photos:["/models/PEYTON/Peyton-12.webp", "/models/PEYTON/Peyton-9.webp", "/models/PEYTON/Peyton-5.webp", "/models/PEYTON/Peyton-3.webp", "/models/PEYTON/Peyton-4.webp", "/models/PEYTON/Peyton-7.webp", "/models/PEYTON/Peyton-2.webp", "/models/PEYTON/Peyton-8.webp", "/models/PEYTON/Peyton-6.webp", "/models/PEYTON/Peyton.webp"] },
  { id:20,name:"SYETA",type:"Musician",img:"/models/SYETA/Syeta-5.webp",loc:"Denver, CO",bio:"Indie folk singer-songwriter. Looking to collab on video projects.",collabs:8,score:72,verified:false,styles:["Experimental", "Documentary", "Commercial"],looking:["Photographer", "Director", "Editor"],connection:"collab",nsfw:false,online:false,zodiac:"Leo",chinese:"Tiger",mbti:"ENTP",lifePath:7,badges:[{name: "Match Magnet", desc: "10+ matches this month", icon: "\u2661", color: "#FF69B4"}, {name: "Quick Responder", desc: "Responds within 2 hours", icon: "\u26a1", color: "#FFD700"}],photos:["/models/SYETA/Syeta-5.webp", "/models/SYETA/Syeta-2.webp", "/models/SYETA/Syeta-9.webp", "/models/SYETA/Syeta-4.webp", "/models/SYETA/Syeta-14.webp", "/models/SYETA/Syeta-15.webp", "/models/SYETA/Syeta-17.webp", "/models/SYETA/Syeta-3.webp", "/models/SYETA/Syeta-6.webp"] },
  { id:21,name:"WESLEY",type:"Director",img:"/models/WESLEY/Wesley-17.webp",loc:"Chicago, IL",bio:"Indie filmmaker obsessed with practical effects.",collabs:27,score:88,verified:true,styles:["Experimental", "Music Video", "Documentary"],looking:["Photographer", "Director"],connection:"mentor",nsfw:false,online:false,zodiac:"Virgo",chinese:"Dog",mbti:"ISTP",lifePath:22,badges:[{name: "Verified Pro", desc: "Identity verified by Muse", icon: "\u2713", color: "#FFD700"}, {name: "Match Magnet", desc: "10+ matches this month", icon: "\u2661", color: "#FF69B4"}, {name: "Super Collab", desc: "High match compatibility", icon: "\u2661", color: "#FF69B4"}, {name: "Style Icon", desc: "Recognized for outstanding style", icon: "\u2726", color: "#D4A5FF"}],photos:["/models/WESLEY/Wesley-17.webp", "/models/WESLEY/Wesley-26.webp", "/models/WESLEY/Wesley-18.webp", "/models/WESLEY/Wesley-20.webp", "/models/WESLEY/Wesley-13.webp", "/models/WESLEY/Wesley-12.webp", "/models/WESLEY/Wesley-25.webp", "/models/WESLEY/Wesley-15.webp", "/models/WESLEY/Wesley-10.webp", "/models/WESLEY/Wesley-14.webp"] },
  { id:22,name:"ADRIENNE",type:"Editor",img:"/models/ADRIENNE/Adrienne 1.webp",loc:"Nashville, TN",bio:"Pixel surgeon. Craft in every cut.",collabs:66,score:73,verified:true,styles:["Dark", "Fashion", "Vintage", "Branding"],looking:["Director", "Designer"],connection:"mentor",nsfw:false,online:true,zodiac:"Cancer",chinese:"Rat",mbti:"ESFP",lifePath:7,badges:[{name: "Quick Responder", desc: "Responds within 2 hours", icon: "⚡", color: "#FFD700"}, {name: "Verified Pro", desc: "Identity verified by Muse", icon: "✓", color: "#FFD700"}, {name: "Local Legend", desc: "Top creative in their city", icon: "📍", color: "#87CEEB"}, {name: "Creative Sage", desc: "47+ collaborations completed", icon: "◊", color: "#FFB5C2"}],photos:["/models/ADRIENNE/Adrienne 1.webp", "/models/ADRIENNE/Adrienne 10.webp", "/models/ADRIENNE/Adrienne 12.webp", "/models/ADRIENNE/Adrienne 13.webp", "/models/ADRIENNE/Adrienne 14.webp", "/models/ADRIENNE/Adrienne 3.webp", "/models/ADRIENNE/Adrienne 4.webp", "/models/ADRIENNE/Adrienne 6.webp", "/models/ADRIENNE/Adrienne 8.webp", "/models/ADRIENNE/Adrienne 9.webp"] },
  { id:23,name:"AECH DOT",type:"Videographer",img:"/models/AECH_DOT/20171112185026_IMG_0926.webp",loc:"Seattle, WA",bio:"Drone cinematography and landscape films.",collabs:64,score:91,verified:false,styles:["Branding", "Music Video", "Dreamy"],looking:["Editor", "Videographer"],connection:"partner",nsfw:false,online:false,zodiac:"Gemini",chinese:"Rat",mbti:"ISTJ",lifePath:6,badges:[{name: "Top Creator", desc: "80+ collaborations completed", icon: "★", color: "#FF8A80"}, {name: "Verified Pro", desc: "Identity verified by Muse", icon: "✓", color: "#FFD700"}, {name: "Super Collab", desc: "High match compatibility", icon: "♥", color: "#FF69B4"}, {name: "Match Magnet", desc: "10+ matches this month", icon: "♥", color: "#FF69B4"}],photos:["/models/AECH_DOT/20171112185026_IMG_0926.webp", "/models/AECH_DOT/Copy of Studio Shoot-5.webp", "/models/AECH_DOT/Copy of Studio Shoot-56.webp", "/models/AECH_DOT/Dot-15.webp", "/models/AECH_DOT/Dot-25.webp", "/models/AECH_DOT/Video Shoot (10 of 39).webp", "/models/AECH_DOT/Video Shoot (12 of 39).webp", "/models/AECH_DOT/Video Shoot (141 of 171).webp", "/models/AECH_DOT/Video Shoot (16 of 171).webp", "/models/AECH_DOT/Video Shoot (17 of 39).webp"] },
  { id:24,name:"AJA",type:"Director",img:"/models/AJA/Aja-10.webp",loc:"Chicago, IL",bio:"Obsessed with practical effects and raw emotion.",collabs:116,score:89,verified:true,styles:["Dreamy", "Portrait", "Experimental"],looking:["Photographer", "Designer"],connection:"mentor",nsfw:false,online:true,zodiac:"Scorpio",chinese:"Ox",mbti:"ISTP",lifePath:6,badges:[{name: "Creative Sage", desc: "47+ collaborations completed", icon: "◊", color: "#FFB5C2"}, {name: "Rising Star", desc: "New to Muse, gaining traction", icon: "✦", color: "#98FB98"}, {name: "Verified Pro", desc: "Identity verified by Muse", icon: "✓", color: "#FFD700"}, {name: "Quick Responder", desc: "Responds within 2 hours", icon: "⚡", color: "#FFD700"}],photos:["/models/AJA/Aja-10.webp", "/models/AJA/Aja-2.webp", "/models/AJA/Aja-3.webp", "/models/AJA/Aja-4.webp", "/models/AJA/Aja-5.webp", "/models/AJA/Aja-6.webp", "/models/AJA/Aja-7.webp", "/models/AJA/Aja-8.webp", "/models/AJA/Aja.webp"] },
  { id:25,name:"ANGEL",type:"Content Creator",img:"/models/ANGEL/Angel-129.webp",loc:"New York, NY",bio:"Digital storyteller and content alchemist.",collabs:55,score:89,verified:false,styles:["Fine Art", "Commercial"],looking:["Director", "Editor"],connection:"friend",nsfw:false,online:false,zodiac:"Leo",chinese:"Ox",mbti:"ISFJ",lifePath:11,badges:[{name: "Local Legend", desc: "Top creative in their city", icon: "📍", color: "#87CEEB"}, {name: "Quick Responder", desc: "Responds within 2 hours", icon: "⚡", color: "#FFD700"}],photos:["/models/ANGEL/Angel-129.webp", "/models/ANGEL/Angel-15.webp", "/models/ANGEL/Angel-176.webp", "/models/ANGEL/Angel-2.webp", "/models/ANGEL/Angel-220.webp", "/models/ANGEL/Angel-225.webp", "/models/ANGEL/Angel-264.webp", "/models/ANGEL/Angel-65.webp", "/models/ANGEL/Angel-71.webp", "/models/ANGEL/Angel-71_1.webp"] },
  { id:26,name:"ANGELICA",type:"Producer",img:"/models/ANGELICA/ANGELICA-124.webp",loc:"San Francisco, CA",bio:"Making creative chaos look effortless.",collabs:68,score:79,verified:true,styles:["Music Video", "Abstract", "Commercial"],looking:["Videographer", "Producer"],connection:"friend",nsfw:false,online:false,zodiac:"Aquarius",chinese:"Monkey",mbti:"INFP",lifePath:5,badges:[{name: "Creative Sage", desc: "47+ collaborations completed", icon: "◊", color: "#FFB5C2"}, {name: "Super Collab", desc: "High match compatibility", icon: "♥", color: "#FF69B4"}],photos:["/models/ANGELICA/ANGELICA-124.webp", "/models/ANGELICA/ANGELICA-133.webp", "/models/ANGELICA/ANGELICA-141.webp", "/models/ANGELICA/ANGELICA-162.webp", "/models/ANGELICA/ANGELICA-171.webp", "/models/ANGELICA/ANGELICA-193.webp", "/models/ANGELICA/ANGELICA-263.webp", "/models/ANGELICA/ANGELICA-272.webp", "/models/ANGELICA/ANGELICA-289.webp", "/models/ANGELICA/ANGELICA-92.webp"] },
  { id:27,name:"ANTHONIA",type:"Designer",img:"/models/ANTHONIA/Antonia-25.webp",loc:"Seattle, WA",bio:"Typography and layout enthusiast.",collabs:57,score:82,verified:false,styles:["Dark", "Abstract", "Fine Art"],looking:["Designer", "Musician"],connection:"partner",nsfw:false,online:true,zodiac:"Cancer",chinese:"Rooster",mbti:"ESFP",lifePath:6,badges:[{name: "Rising Star", desc: "New to Muse, gaining traction", icon: "✦", color: "#98FB98"}, {name: "Verified Pro", desc: "Identity verified by Muse", icon: "✓", color: "#FFD700"}],photos:["/models/ANTHONIA/Antonia-25.webp", "/models/ANTHONIA/Antonia-26.webp", "/models/ANTHONIA/Antonia-32.webp", "/models/ANTHONIA/Antonia-74.webp", "/models/ANTHONIA/Retouched-3.webp"] },
  { id:28,name:"ASH",type:"Model",img:"/models/ASH/Ash (21 of 69).webp",loc:"Las Vegas, NV",bio:"Movement and light are my mediums.",collabs:116,score:84,verified:false,styles:["Bold", "Fine Art"],looking:["Designer", "Videographer", "Director"],connection:"mentor",nsfw:false,online:false,zodiac:"Leo",chinese:"Rabbit",mbti:"ENFJ",lifePath:22,badges:[{name: "Local Legend", desc: "Top creative in their city", icon: "📍", color: "#87CEEB"}, {name: "Super Collab", desc: "High match compatibility", icon: "♥", color: "#FF69B4"}, {name: "Style Icon", desc: "Recognized for outstanding style", icon: "✦", color: "#D4A5FF"}, {name: "Rising Star", desc: "New to Muse, gaining traction", icon: "✦", color: "#98FB98"}],photos:["/models/ASH/Ash (21 of 69).webp", "/models/ASH/Ash (22 of 69).webp", "/models/ASH/Ash (26 of 69).webp", "/models/ASH/Ash (29 of 69).webp", "/models/ASH/Ash (3 of 7).webp", "/models/ASH/Ash (31 of 69).webp", "/models/ASH/Ash (4 of 7).webp", "/models/ASH/Ash (47 of 69).webp", "/models/ASH/Ash (56 of 69).webp", "/models/ASH/Ash (67 of 69).webp"] },
  { id:29,name:"ASHONDI",type:"Editor",img:"/models/ASHONDI/Ashondi-128.webp",loc:"Austin, TX",bio:"Where stories find their rhythm.",collabs:69,score:76,verified:true,styles:["Portrait", "Abstract", "Music Video"],looking:["Editor", "Director", "Musician"],connection:"friend",nsfw:false,online:true,zodiac:"Scorpio",chinese:"Rooster",mbti:"INTP",lifePath:2,badges:[{name: "Verified Pro", desc: "Identity verified by Muse", icon: "✓", color: "#FFD700"}, {name: "Quick Responder", desc: "Responds within 2 hours", icon: "⚡", color: "#FFD700"}],photos:["/models/ASHONDI/Ashondi-128.webp", "/models/ASHONDI/Ashondi-131.webp", "/models/ASHONDI/Ashondi-154.webp", "/models/ASHONDI/Ashondi-196.webp", "/models/ASHONDI/Ashondi-266.webp", "/models/ASHONDI/Ashondi-287.webp", "/models/ASHONDI/Ashondi-3.webp", "/models/ASHONDI/Ashondi-304.webp", "/models/ASHONDI/Ashondi-352.webp", "/models/ASHONDI/Ashondi-71.webp"] },
  { id:30,name:"BRIAN",type:"Stylist",img:"/models/BRIAN/Retouched-2.webp",loc:"Los Angeles, CA",bio:"Curating looks that tell stories.",collabs:119,score:84,verified:true,styles:["Branding", "Music Video", "Body Art", "Documentary"],looking:["Designer", "Musician"],connection:"friend",nsfw:false,online:false,zodiac:"Aries",chinese:"Dog",mbti:"ESFJ",lifePath:6,badges:[{name: "Top Creator", desc: "80+ collaborations completed", icon: "★", color: "#FF8A80"}, {name: "Creative Sage", desc: "47+ collaborations completed", icon: "◊", color: "#FFB5C2"}],photos:["/models/BRIAN/Retouched-2.webp", "/models/BRIAN/Shoot-152.webp", "/models/BRIAN/Shoot-174.webp", "/models/BRIAN/Shoot-175.webp", "/models/BRIAN/Shoot-202.webp", "/models/BRIAN/Shoot-206.webp", "/models/BRIAN/Shoot-213.webp", "/models/BRIAN/Shoot-236.webp", "/models/BRIAN/Shoot-242.webp", "/models/BRIAN/Shoot-246.webp"] },
  { id:31,name:"BRIYANNA",type:"Writer",img:"/models/BRIYANNA/Bri'Yanna-117.webp",loc:"Atlanta, GA",bio:"Wordsmith crafting narratives.",collabs:24,score:90,verified:true,styles:["Vintage", "Film"],looking:["Videographer", "Director"],connection:"partner",nsfw:false,online:false,zodiac:"Pisces",chinese:"Goat",mbti:"ESTJ",lifePath:33,badges:[{name: "Creative Sage", desc: "47+ collaborations completed", icon: "◊", color: "#FFB5C2"}, {name: "Rising Star", desc: "New to Muse, gaining traction", icon: "✦", color: "#98FB98"}, {name: "Local Legend", desc: "Top creative in their city", icon: "📍", color: "#87CEEB"}, {name: "Verified Pro", desc: "Identity verified by Muse", icon: "✓", color: "#FFD700"}],photos:["/models/BRIYANNA/Bri'Yanna-117.webp", "/models/BRIYANNA/Bri'Yanna-123.webp", "/models/BRIYANNA/Bri'Yanna-142.webp", "/models/BRIYANNA/Bri'Yanna-146.webp", "/models/BRIYANNA/Bri'Yanna-171.webp", "/models/BRIYANNA/Bri'Yanna-210.webp", "/models/BRIYANNA/Bri'Yanna-27.webp", "/models/BRIYANNA/Bri'Yanna-83.webp", "/models/BRIYANNA/Bri'Yanna-92.webp", "/models/BRIYANNA/Bri'Yanna.webp"] },
  { id:32,name:"BROCK",type:"Videographer",img:"/models/BROCK/IMG_1638.webp",loc:"Nashville, TN",bio:"Drone cinematography and landscape films.",collabs:90,score:87,verified:true,styles:["Vintage", "Branding"],looking:["Director", "Musician"],connection:"friend",nsfw:false,online:false,zodiac:"Sagittarius",chinese:"Rabbit",mbti:"INFP",lifePath:33,badges:[{name: "Super Collab", desc: "High match compatibility", icon: "♥", color: "#FF69B4"}, {name: "Style Icon", desc: "Recognized for outstanding style", icon: "✦", color: "#D4A5FF"}, {name: "Local Legend", desc: "Top creative in their city", icon: "📍", color: "#87CEEB"}, {name: "Match Magnet", desc: "10+ matches this month", icon: "♥", color: "#FF69B4"}],photos:["/models/BROCK/IMG_1638.webp", "/models/BROCK/IMG_1639.webp", "/models/BROCK/IMG_1641.webp", "/models/BROCK/IMG_1666.webp", "/models/BROCK/IMG_1671.webp", "/models/BROCK/IMG_1725.webp", "/models/BROCK/IMG_1727.webp", "/models/BROCK/IMG_1893.webp", "/models/BROCK/IMG_1899.webp", "/models/BROCK/IMG_1901.webp"] },
  { id:33,name:"BROOK",type:"Actor",img:"/models/BROOK/Brooke-103.webp",loc:"San Francisco, CA",bio:"Bringing authenticity to every role.",collabs:81,score:76,verified:false,styles:["Dark", "Editorial", "Fashion"],looking:["Producer", "Photographer"],connection:"partner",nsfw:false,online:true,zodiac:"Taurus",chinese:"Rat",mbti:"ESTP",lifePath:7,badges:[{name: "Quick Responder", desc: "Responds within 2 hours", icon: "⚡", color: "#FFD700"}, {name: "Rising Star", desc: "New to Muse, gaining traction", icon: "✦", color: "#98FB98"}, {name: "Style Icon", desc: "Recognized for outstanding style", icon: "✦", color: "#D4A5FF"}],photos:["/models/BROOK/Brooke-103.webp", "/models/BROOK/Brooke-11.webp", "/models/BROOK/Brooke-124.webp", "/models/BROOK/Brooke-131.webp", "/models/BROOK/Brooke-137.webp", "/models/BROOK/Brooke-143 (1).webp", "/models/BROOK/Brooke-33.webp", "/models/BROOK/Brooke-35.webp", "/models/BROOK/Brooke-74.webp", "/models/BROOK/Brooke-9.webp"] },
  { id:34,name:"BROOKE",type:"MUA",img:"/models/BROOKE/Bodypaint-357.webp",loc:"Seattle, WA",bio:"Makeup as self-expression.",collabs:91,score:71,verified:true,styles:["Editorial", "Dark", "Bold", "Branding"],looking:["Designer", "Photographer", "Producer"],connection:"partner",nsfw:false,online:true,zodiac:"Libra",chinese:"Rabbit",mbti:"ISFP",lifePath:4,badges:[{name: "Match Magnet", desc: "10+ matches this month", icon: "♥", color: "#FF69B4"}, {name: "Rising Star", desc: "New to Muse, gaining traction", icon: "✦", color: "#98FB98"}, {name: "Creative Sage", desc: "47+ collaborations completed", icon: "◊", color: "#FFB5C2"}, {name: "Super Collab", desc: "High match compatibility", icon: "♥", color: "#FF69B4"}],photos:["/models/BROOKE/Bodypaint-357.webp", "/models/BROOKE/Bodypaint-399.webp", "/models/BROOKE/Bodypaint-413.webp", "/models/BROOKE/Brooke-108.webp", "/models/BROOKE/Brooke-66.webp", "/models/BROOKE/Chinatown-11.webp", "/models/BROOKE/Chinatown-167.webp", "/models/BROOKE/Chinatown-307.webp", "/models/BROOKE/Chinatown-58.webp", "/models/BROOKE/Chinatown-65.webp"] },
  { id:35,name:"CITLALI",type:"Content Creator",img:"/models/CITLALI/Bodypaint-120.webp",loc:"Seattle, WA",bio:"Turning ideas into viral moments.",collabs:84,score:75,verified:false,styles:["Experimental", "Bold", "Dark"],looking:["Designer", "Writer", "Musician"],connection:"collab",nsfw:false,online:false,zodiac:"Cancer",chinese:"Dog",mbti:"ISFJ",lifePath:11,badges:[{name: "Super Collab", desc: "High match compatibility", icon: "♥", color: "#FF69B4"}, {name: "Quick Responder", desc: "Responds within 2 hours", icon: "⚡", color: "#FFD700"}, {name: "Creative Sage", desc: "47+ collaborations completed", icon: "◊", color: "#FFB5C2"}, {name: "Match Magnet", desc: "10+ matches this month", icon: "♥", color: "#FF69B4"}],photos:["/models/CITLALI/Bodypaint-120.webp", "/models/CITLALI/Bodypaint-25.webp", "/models/CITLALI/Bodypaint-55.webp", "/models/CITLALI/Bodypaint-77.webp", "/models/CITLALI/Bodypaint-83.webp", "/models/CITLALI/Bodypaint-88.webp", "/models/CITLALI/Citlali-131.webp", "/models/CITLALI/Citlali-53.webp", "/models/CITLALI/Citlali-79.webp", "/models/CITLALI/Citlali-94.webp"] },
  { id:36,name:"CLAUDIA",type:"Photographer",img:"/models/CLAUDIA/Claudia-17.webp",loc:"Chicago, IL",bio:"Storyteller through the lens.",collabs:107,score:77,verified:true,styles:["Vintage", "Music Video", "Experimental", "Dreamy"],looking:["Designer", "Musician"],connection:"collab",nsfw:false,online:true,zodiac:"Leo",chinese:"Rabbit",mbti:"ESTJ",lifePath:2,badges:[{name: "Match Magnet", desc: "10+ matches this month", icon: "♥", color: "#FF69B4"}, {name: "Local Legend", desc: "Top creative in their city", icon: "📍", color: "#87CEEB"}, {name: "Style Icon", desc: "Recognized for outstanding style", icon: "✦", color: "#D4A5FF"}, {name: "Top Creator", desc: "80+ collaborations completed", icon: "★", color: "#FF8A80"}],photos:["/models/CLAUDIA/Claudia-17.webp", "/models/CLAUDIA/Claudia-18.webp", "/models/CLAUDIA/Claudia-19.webp", "/models/CLAUDIA/Claudia-20.webp", "/models/CLAUDIA/Claudia-21.webp", "/models/CLAUDIA/Claudia-22.webp", "/models/CLAUDIA/Claudia-23.webp", "/models/CLAUDIA/Claudia-24.webp", "/models/CLAUDIA/Claudia-25.webp", "/models/CLAUDIA/Claudia-26.webp"] },
  { id:37,name:"CORI",type:"Stylist",img:"/models/CORI/Cori-109.webp",loc:"New York, NY",bio:"Fashion is my language.",collabs:21,score:73,verified:true,styles:["Documentary", "Music Video"],looking:["Editor", "Videographer", "Writer"],connection:"partner",nsfw:false,online:false,zodiac:"Leo",chinese:"Snake",mbti:"ENTJ",lifePath:4,badges:[{name: "Match Magnet", desc: "10+ matches this month", icon: "♥", color: "#FF69B4"}, {name: "Rising Star", desc: "New to Muse, gaining traction", icon: "✦", color: "#98FB98"}, {name: "Creative Sage", desc: "47+ collaborations completed", icon: "◊", color: "#FFB5C2"}],photos:["/models/CORI/Cori-109.webp", "/models/CORI/Cori-120.webp", "/models/CORI/Cori-123.webp", "/models/CORI/Cori-131.webp", "/models/CORI/Cori-132.webp", "/models/CORI/Cori-30.webp", "/models/CORI/Cori-34.webp", "/models/CORI/Cori-81.webp", "/models/CORI/Cori-99.webp", "/models/CORI/Cori.webp"] },
  { id:38,name:"CRISTINA",type:"Actor",img:"/models/CRISTINA/20171120110140_IMG_2185.webp",loc:"New York, NY",bio:"Character-driven performer.",collabs:59,score:82,verified:true,styles:["Vintage", "Music Video", "Film", "Portrait"],looking:["Producer", "Writer"],connection:"collab",nsfw:false,online:true,zodiac:"Libra",chinese:"Rabbit",mbti:"ESTP",lifePath:9,badges:[{name: "Verified Pro", desc: "Identity verified by Muse", icon: "✓", color: "#FFD700"}, {name: "Creative Sage", desc: "47+ collaborations completed", icon: "◊", color: "#FFB5C2"}],photos:["/models/CRISTINA/20171120110140_IMG_2185.webp", "/models/CRISTINA/20171120110457_IMG_2191.webp", "/models/CRISTINA/20171120110642_IMG_2207.webp", "/models/CRISTINA/20171120111920_IMG_2342.webp", "/models/CRISTINA/20171120112317_IMG_2391.webp", "/models/CRISTINA/20171120112552_IMG_2418.webp", "/models/CRISTINA/20171120113818_IMG_2579.webp", "/models/CRISTINA/20171120114102_IMG_2626.webp", "/models/CRISTINA/20171120120844_IMG_2758.webp", "/models/CRISTINA/20171120120948_IMG_2769.webp"] },
  { id:39,name:"DANIELLE",type:"Writer",img:"/models/DANIELLE/Danielle-117.webp",loc:"Chicago, IL",bio:"Wordsmith crafting narratives.",collabs:59,score:95,verified:true,styles:["Branding", "Editorial", "Body Art"],looking:["Producer", "Musician"],connection:"friend",nsfw:false,online:false,zodiac:"Sagittarius",chinese:"Goat",mbti:"ESFP",lifePath:6,badges:[{name: "Top Creator", desc: "80+ collaborations completed", icon: "★", color: "#FF8A80"}, {name: "Quick Responder", desc: "Responds within 2 hours", icon: "⚡", color: "#FFD700"}, {name: "Rising Star", desc: "New to Muse, gaining traction", icon: "✦", color: "#98FB98"}],photos:["/models/DANIELLE/Danielle-117.webp", "/models/DANIELLE/Danielle-123.webp", "/models/DANIELLE/Danielle-124.webp", "/models/DANIELLE/Danielle-126.webp", "/models/DANIELLE/Danielle-218.webp", "/models/DANIELLE/Danielle-221.webp", "/models/DANIELLE/Danielle-227.webp", "/models/DANIELLE/Danielle-233.webp", "/models/DANIELLE/Danielle-26.webp", "/models/DANIELLE/Danielle-287.webp"] },
  { id:40,name:"DARRYL",type:"Videographer",img:"/models/DARRYL/Darryl-10.webp",loc:"Nashville, TN",bio:"Capturing motion and emotion.",collabs:83,score:71,verified:false,styles:["Vintage", "Music Video"],looking:["Musician", "Writer"],connection:"partner",nsfw:false,online:false,zodiac:"Sagittarius",chinese:"Dragon",mbti:"INFP",lifePath:2,badges:[{name: "Verified Pro", desc: "Identity verified by Muse", icon: "✓", color: "#FFD700"}, {name: "Creative Sage", desc: "47+ collaborations completed", icon: "◊", color: "#FFB5C2"}, {name: "Rising Star", desc: "New to Muse, gaining traction", icon: "✦", color: "#98FB98"}, {name: "Match Magnet", desc: "10+ matches this month", icon: "♥", color: "#FF69B4"}],photos:["/models/DARRYL/Darryl-10.webp", "/models/DARRYL/Darryl-102.webp", "/models/DARRYL/Darryl-16.webp", "/models/DARRYL/Darryl-2.webp", "/models/DARRYL/Darryl-34.webp", "/models/DARRYL/Darryl-37.webp", "/models/DARRYL/Darryl-38.webp", "/models/DARRYL/Darryl-45.webp", "/models/DARRYL/Darryl-48.webp", "/models/DARRYL/Darryl-55.webp"] },
  { id:41,name:"DOT",type:"Stylist",img:"/models/DOT/20171112184254_IMG_0870.webp",loc:"San Francisco, CA",bio:"Fashion is my language.",collabs:90,score:80,verified:false,styles:["Abstract", "Editorial"],looking:["Designer", "Musician"],connection:"collab",nsfw:false,online:true,zodiac:"Pisces",chinese:"Dragon",mbti:"ENTJ",lifePath:7,badges:[{name: "Rising Star", desc: "New to Muse, gaining traction", icon: "✦", color: "#98FB98"}, {name: "Creative Sage", desc: "47+ collaborations completed", icon: "◊", color: "#FFB5C2"}, {name: "Quick Responder", desc: "Responds within 2 hours", icon: "⚡", color: "#FFD700"}],photos:["/models/DOT/20171112184254_IMG_0870.webp", "/models/DOT/20171112205718__MG_1350.webp", "/models/DOT/20171112205724__MG_1355.webp", "/models/DOT/Dot-12.webp", "/models/DOT/Dot-21.webp", "/models/DOT/Dot-3.webp", "/models/DOT/Dot-5.webp", "/models/DOT/Video Shoot (147 of 171).webp", "/models/DOT/Video Shoot (16 of 39).webp", "/models/DOT/Video Shoot (18 of 171).webp"] },
  { id:42,name:"DRAKE",type:"Editor",img:"/models/DRAKE/Blah-167.webp",loc:"Nashville, TN",bio:"Where stories find their rhythm.",collabs:101,score:74,verified:false,styles:["Fashion", "Branding", "Experimental", "Dark"],looking:["Designer", "Editor", "Director"],connection:"collab",nsfw:false,online:true,zodiac:"Aries",chinese:"Goat",mbti:"ESFP",lifePath:5,badges:[{name: "Creative Sage", desc: "47+ collaborations completed", icon: "◊", color: "#FFB5C2"}, {name: "Super Collab", desc: "High match compatibility", icon: "♥", color: "#FF69B4"}, {name: "Quick Responder", desc: "Responds within 2 hours", icon: "⚡", color: "#FFD700"}],photos:["/models/DRAKE/Blah-167.webp", "/models/DRAKE/Blah-196.webp", "/models/DRAKE/Blah-65.webp", "/models/DRAKE/Drake-10.webp", "/models/DRAKE/Drake-150.webp", "/models/DRAKE/Drake-185.webp", "/models/DRAKE/Shoot-120.webp", "/models/DRAKE/Shoot-45.webp", "/models/DRAKE/Shoot-85.webp", "/models/DRAKE/South Loop-295.webp"] },
  { id:43,name:"EBONY",type:"Director",img:"/models/EBONY/Apartment-122.webp",loc:"Nashville, TN",bio:"Obsessed with practical effects and raw emotion.",collabs:47,score:87,verified:true,styles:["Film", "Documentary", "Dark"],looking:["Producer", "Editor", "Writer"],connection:"friend",nsfw:false,online:true,zodiac:"Scorpio",chinese:"Rooster",mbti:"INTP",lifePath:22,badges:[{name: "Quick Responder", desc: "Responds within 2 hours", icon: "⚡", color: "#FFD700"}, {name: "Rising Star", desc: "New to Muse, gaining traction", icon: "✦", color: "#98FB98"}],photos:["/models/EBONY/Apartment-122.webp", "/models/EBONY/Apartment-134.webp", "/models/EBONY/Apartment-14.webp", "/models/EBONY/Apartment-224.webp", "/models/EBONY/Apartment-372.webp", "/models/EBONY/Ebony-100.webp", "/models/EBONY/Ebony-109.webp", "/models/EBONY/Ebony-144.webp", "/models/EBONY/Ebony-190.webp", "/models/EBONY/Ebony-228.webp"] },
  { id:44,name:"EDEN",type:"Actor",img:"/models/EDEN/Eden-107.webp",loc:"Miami, FL",bio:"Character-driven performer.",collabs:83,score:93,verified:false,styles:["Fine Art", "Music Video"],looking:["Designer", "Writer", "Photographer"],connection:"partner",nsfw:false,online:true,zodiac:"Pisces",chinese:"Pig",mbti:"ESTJ",lifePath:3,badges:[{name: "Local Legend", desc: "Top creative in their city", icon: "📍", color: "#87CEEB"}, {name: "Verified Pro", desc: "Identity verified by Muse", icon: "✓", color: "#FFD700"}, {name: "Top Creator", desc: "80+ collaborations completed", icon: "★", color: "#FF8A80"}, {name: "Match Magnet", desc: "10+ matches this month", icon: "♥", color: "#FF69B4"}],photos:["/models/EDEN/Eden-107.webp", "/models/EDEN/Eden-111.webp", "/models/EDEN/Eden-122.webp", "/models/EDEN/Eden-2.webp", "/models/EDEN/Eden-52.webp", "/models/EDEN/Eden-71.webp", "/models/EDEN/Eden-8.webp", "/models/EDEN/South Loop-144.webp", "/models/EDEN/South Loop-166.webp", "/models/EDEN/South Loop-38.webp"] },
  { id:45,name:"FARREN",type:"Videographer",img:"/models/FARREN/Bodypaint-103.webp",loc:"New York, NY",bio:"Capturing motion and emotion.",collabs:41,score:89,verified:false,styles:["Commercial", "Experimental", "Body Art"],looking:["Photographer", "Writer"],connection:"friend",nsfw:false,online:false,zodiac:"Libra",chinese:"Dog",mbti:"ISFP",lifePath:6,badges:[{name: "Quick Responder", desc: "Responds within 2 hours", icon: "⚡", color: "#FFD700"}, {name: "Local Legend", desc: "Top creative in their city", icon: "📍", color: "#87CEEB"}, {name: "Top Creator", desc: "80+ collaborations completed", icon: "★", color: "#FF8A80"}],photos:["/models/FARREN/Bodypaint-103.webp", "/models/FARREN/Bodypaint-117.webp", "/models/FARREN/Bodypaint-126.webp", "/models/FARREN/Bodypaint-128.webp", "/models/FARREN/Bodypaint-133.webp", "/models/FARREN/Bodypaint-136.webp", "/models/FARREN/Bodypaint-14.webp", "/models/FARREN/Bodypaint-140.webp", "/models/FARREN/Bodypaint-18.webp", "/models/FARREN/Bodypaint-2.webp"] },
  { id:46,name:"GREYSON",type:"Editor",img:"/models/GREYSON/GREY-101.webp",loc:"Portland, OR",bio:"Where stories find their rhythm.",collabs:22,score:94,verified:false,styles:["Bold", "Editorial"],looking:["Designer", "Photographer"],connection:"collab",nsfw:false,online:true,zodiac:"Libra",chinese:"Dragon",mbti:"ESTP",lifePath:9,badges:[{name: "Super Collab", desc: "High match compatibility", icon: "♥", color: "#FF69B4"}, {name: "Match Magnet", desc: "10+ matches this month", icon: "♥", color: "#FF69B4"}, {name: "Verified Pro", desc: "Identity verified by Muse", icon: "✓", color: "#FFD700"}],photos:["/models/GREYSON/GREY-101.webp", "/models/GREYSON/GREY-108.webp", "/models/GREYSON/GREY-123.webp", "/models/GREYSON/GREY-13.webp", "/models/GREYSON/GREY-141.webp", "/models/GREYSON/GREY-16.webp", "/models/GREYSON/GREY-33.webp", "/models/GREYSON/GREY-34.webp", "/models/GREYSON/GREY-73.webp", "/models/GREYSON/GREY-78.webp"] },
  { id:47,name:"HANNAH",type:"Director",img:"/models/HANNAH/HANNAH (retouched)-10.webp",loc:"Miami, FL",bio:"Obsessed with practical effects and raw emotion.",collabs:76,score:83,verified:true,styles:["Bold", "Vintage"],looking:["Director", "Editor"],connection:"partner",nsfw:false,online:false,zodiac:"Cancer",chinese:"Monkey",mbti:"ISFJ",lifePath:11,badges:[{name: "Quick Responder", desc: "Responds within 2 hours", icon: "⚡", color: "#FFD700"}, {name: "Super Collab", desc: "High match compatibility", icon: "♥", color: "#FF69B4"}, {name: "Verified Pro", desc: "Identity verified by Muse", icon: "✓", color: "#FFD700"}],photos:["/models/HANNAH/HANNAH (retouched)-10.webp", "/models/HANNAH/HANNAH (retouched)-11.webp", "/models/HANNAH/HANNAH (retouched)-12.webp", "/models/HANNAH/HANNAH (retouched)-13.webp", "/models/HANNAH/HANNAH (retouched)-14.webp", "/models/HANNAH/HANNAH (retouched)-15.webp", "/models/HANNAH/HANNAH (retouched)-16.webp", "/models/HANNAH/HANNAH (retouched)-17.webp", "/models/HANNAH/HANNAH (retouched)-2.webp", "/models/HANNAH/HANNAH (retouched)-3.webp"] },
  { id:48,name:"HEADY",type:"Producer",img:"/models/HEADY/Heady Lovell-102.webp",loc:"Nashville, TN",bio:"Project visionary and team builder.",collabs:52,score:72,verified:true,styles:["Editorial", "Body Art"],looking:["Editor", "Videographer"],connection:"collab",nsfw:false,online:false,zodiac:"Gemini",chinese:"Goat",mbti:"INTP",lifePath:3,badges:[{name: "Match Magnet", desc: "10+ matches this month", icon: "♥", color: "#FF69B4"}, {name: "Quick Responder", desc: "Responds within 2 hours", icon: "⚡", color: "#FFD700"}, {name: "Super Collab", desc: "High match compatibility", icon: "♥", color: "#FF69B4"}],photos:["/models/HEADY/Heady Lovell-102.webp", "/models/HEADY/Heady Lovell-120.webp", "/models/HEADY/Heady Lovell-152.webp", "/models/HEADY/Heady Lovell-155.webp", "/models/HEADY/Heady Lovell-167.webp", "/models/HEADY/Heady Lovell-51.webp", "/models/HEADY/Heady Lovell-52.webp", "/models/HEADY/vampire-4.webp", "/models/HEADY/vampire-75.webp", "/models/HEADY/vampire-88.webp"] },
  { id:49,name:"IVY",type:"Editor",img:"/models/IVY/Ivy-104.webp",loc:"New York, NY",bio:"Pixel surgeon. Craft in every cut.",collabs:32,score:74,verified:false,styles:["Body Art", "Fashion", "Portrait"],looking:["Musician", "Designer", "Editor"],connection:"partner",nsfw:false,online:false,zodiac:"Aquarius",chinese:"Tiger",mbti:"ENTJ",lifePath:33,badges:[{name: "Top Creator", desc: "80+ collaborations completed", icon: "★", color: "#FF8A80"}, {name: "Rising Star", desc: "New to Muse, gaining traction", icon: "✦", color: "#98FB98"}, {name: "Creative Sage", desc: "47+ collaborations completed", icon: "◊", color: "#FFB5C2"}],photos:["/models/IVY/Ivy-104.webp", "/models/IVY/Ivy-11.webp", "/models/IVY/Ivy-141.webp", "/models/IVY/Ivy-151.webp", "/models/IVY/Ivy-192.webp", "/models/IVY/Ivy-217.webp", "/models/IVY/Ivy-224.webp", "/models/IVY/Ivy-235.webp", "/models/IVY/Ivy-240.webp", "/models/IVY/Ivy-33.webp"] },
  { id:50,name:"JANELLE",type:"MUA",img:"/models/JANELLE/IMG_1279.webp",loc:"Denver, CO",bio:"Beauty architect. Transforming faces into art.",collabs:42,score:77,verified:true,styles:["Commercial", "Dreamy"],looking:["Videographer", "Writer"],connection:"collab",nsfw:false,online:false,zodiac:"Virgo",chinese:"Rat",mbti:"ENTJ",lifePath:4,badges:[{name: "Creative Sage", desc: "47+ collaborations completed", icon: "◊", color: "#FFB5C2"}, {name: "Rising Star", desc: "New to Muse, gaining traction", icon: "✦", color: "#98FB98"}, {name: "Super Collab", desc: "High match compatibility", icon: "♥", color: "#FF69B4"}],photos:["/models/JANELLE/IMG_1279.webp", "/models/JANELLE/IMG_1336.webp", "/models/JANELLE/IMG_1349.webp", "/models/JANELLE/IMG_1753.webp", "/models/JANELLE/IMG_1761.webp", "/models/JANELLE/IMG_1769.webp", "/models/JANELLE/IMG_1785.webp", "/models/JANELLE/IMG_1855.webp", "/models/JANELLE/IMG_1867.webp", "/models/JANELLE/IMG_3415.webp"] },
  { id:51,name:"JERMAINE",type:"Actor",img:"/models/JERMAINE/Jermaine-20.webp",loc:"Portland, OR",bio:"Bringing authenticity to every role.",collabs:69,score:80,verified:true,styles:["Dreamy", "Fine Art"],looking:["Producer", "Writer", "Director"],connection:"collab",nsfw:false,online:false,zodiac:"Cancer",chinese:"Tiger",mbti:"INFP",lifePath:9,badges:[{name: "Quick Responder", desc: "Responds within 2 hours", icon: "⚡", color: "#FFD700"}, {name: "Style Icon", desc: "Recognized for outstanding style", icon: "✦", color: "#D4A5FF"}, {name: "Creative Sage", desc: "47+ collaborations completed", icon: "◊", color: "#FFB5C2"}, {name: "Match Magnet", desc: "10+ matches this month", icon: "♥", color: "#FF69B4"}],photos:["/models/JERMAINE/Jermaine-20.webp", "/models/JERMAINE/Jermaine-23.webp", "/models/JERMAINE/Jermaine-27.webp", "/models/JERMAINE/Jermaine-38.webp", "/models/JERMAINE/Jermaine-51.webp", "/models/JERMAINE/Jermaine-72.webp", "/models/JERMAINE/Jermaine-77.webp", "/models/JERMAINE/Jermaine-90.webp", "/models/JERMAINE/Jermaine-95.webp", "/models/JERMAINE/Jermaine.webp"] },
  { id:52,name:"JIMMY",type:"Writer",img:"/models/JIMMY/Chinatown-52.webp",loc:"New York, NY",bio:"Between the pages and the screen.",collabs:59,score:72,verified:true,styles:["Editorial", "Music Video", "Abstract"],looking:["Writer", "Producer"],connection:"partner",nsfw:false,online:true,zodiac:"Virgo",chinese:"Rooster",mbti:"ENFP",lifePath:4,badges:[{name: "Quick Responder", desc: "Responds within 2 hours", icon: "⚡", color: "#FFD700"}, {name: "Verified Pro", desc: "Identity verified by Muse", icon: "✓", color: "#FFD700"}, {name: "Style Icon", desc: "Recognized for outstanding style", icon: "✦", color: "#D4A5FF"}, {name: "Top Creator", desc: "80+ collaborations completed", icon: "★", color: "#FF8A80"}],photos:["/models/JIMMY/Chinatown-52.webp", "/models/JIMMY/Headshot-10.webp", "/models/JIMMY/Jimmy-110.webp", "/models/JIMMY/Jimmy-114.webp", "/models/JIMMY/Jimmy-130.webp", "/models/JIMMY/Jimmy-24(1).webp", "/models/JIMMY/Jimmy-32.webp", "/models/JIMMY/Jimmy-48.webp", "/models/JIMMY/Jimmy-89.webp", "/models/JIMMY/Jimmy.webp"] },
  { id:53,name:"KATARA",type:"Model",img:"/models/KATARA/Katara-10.webp",loc:"Miami, FL",bio:"Movement and light are my mediums.",collabs:39,score:81,verified:true,styles:["Vintage", "Dark", "Film", "Bold"],looking:["Producer", "Videographer"],connection:"friend",nsfw:false,online:false,zodiac:"Aquarius",chinese:"Horse",mbti:"ENFJ",lifePath:9,badges:[{name: "Super Collab", desc: "High match compatibility", icon: "♥", color: "#FF69B4"}, {name: "Verified Pro", desc: "Identity verified by Muse", icon: "✓", color: "#FFD700"}, {name: "Creative Sage", desc: "47+ collaborations completed", icon: "◊", color: "#FFB5C2"}, {name: "Match Magnet", desc: "10+ matches this month", icon: "♥", color: "#FF69B4"}],photos:["/models/KATARA/Katara-10.webp", "/models/KATARA/Katara-11.webp", "/models/KATARA/Katara-12.webp", "/models/KATARA/Katara-13.webp", "/models/KATARA/Katara-14.webp", "/models/KATARA/Katara-15.webp", "/models/KATARA/Katara-16.webp", "/models/KATARA/Katara-17.webp", "/models/KATARA/Katara-18.webp", "/models/KATARA/Katara-19.webp"] },
  { id:54,name:"KAYLEN",type:"Videographer",img:"/models/KAYLEN/kaylen (retouched)-10.webp",loc:"Portland, OR",bio:"Capturing motion and emotion.",collabs:32,score:72,verified:true,styles:["Fine Art", "Branding", "Music Video"],looking:["Musician", "Director", "Photographer"],connection:"friend",nsfw:false,online:true,zodiac:"Scorpio",chinese:"Rat",mbti:"INFJ",lifePath:7,badges:[{name: "Verified Pro", desc: "Identity verified by Muse", icon: "✓", color: "#FFD700"}, {name: "Super Collab", desc: "High match compatibility", icon: "♥", color: "#FF69B4"}, {name: "Top Creator", desc: "80+ collaborations completed", icon: "★", color: "#FF8A80"}],photos:["/models/KAYLEN/kaylen (retouched)-10.webp", "/models/KAYLEN/kaylen (retouched)-25.webp", "/models/KAYLEN/kaylen (retouched)-30.webp", "/models/KAYLEN/kaylen (retouched)-31.webp", "/models/KAYLEN/kaylen (retouched)-45.webp", "/models/KAYLEN/kaylen (retouched)-6.webp", "/models/KAYLEN/kaylen (retouched)-7.webp", "/models/KAYLEN/kaylen (retouched).webp", "/models/KAYLEN/kaylen-111.webp", "/models/KAYLEN/kaylen-142.webp"] },
  { id:55,name:"KIDLYN",type:"Director",img:"/models/KIDLYN/Kidlyn-11.webp",loc:"Chicago, IL",bio:"Building worlds one frame at a time.",collabs:8,score:94,verified:true,styles:["Branding", "Portrait", "Dark", "Fashion"],looking:["Editor", "Writer"],connection:"partner",nsfw:false,online:true,zodiac:"Pisces",chinese:"Rooster",mbti:"INTJ",lifePath:22,badges:[{name: "Rising Star", desc: "New to Muse, gaining traction", icon: "✦", color: "#98FB98"}, {name: "Match Magnet", desc: "10+ matches this month", icon: "♥", color: "#FF69B4"}, {name: "Creative Sage", desc: "47+ collaborations completed", icon: "◊", color: "#FFB5C2"}, {name: "Quick Responder", desc: "Responds within 2 hours", icon: "⚡", color: "#FFD700"}],photos:["/models/KIDLYN/Kidlyn-11.webp", "/models/KIDLYN/Kidlyn-13.webp", "/models/KIDLYN/Kidlyn-2.webp", "/models/KIDLYN/Kidlyn-3.webp", "/models/KIDLYN/Kidlyn-5.webp", "/models/KIDLYN/Kidlyn-6.webp", "/models/KIDLYN/Kidlyn-7.webp", "/models/KIDLYN/Kidlyn-8.webp", "/models/KIDLYN/Kidlyn-9.webp", "/models/KIDLYN/Kidlyn.webp"] },
  { id:56,name:"LAUREN",type:"Content Creator",img:"/models/LAUREN/Bodypaint-10.webp",loc:"Nashville, TN",bio:"Digital storyteller and content alchemist.",collabs:67,score:86,verified:true,styles:["Vintage", "Dreamy", "Body Art"],looking:["Musician", "Director"],connection:"mentor",nsfw:false,online:true,zodiac:"Gemini",chinese:"Rat",mbti:"ESTJ",lifePath:6,badges:[{name: "Local Legend", desc: "Top creative in their city", icon: "📍", color: "#87CEEB"}, {name: "Super Collab", desc: "High match compatibility", icon: "♥", color: "#FF69B4"}],photos:["/models/LAUREN/Bodypaint-10.webp", "/models/LAUREN/Bodypaint-24.webp", "/models/LAUREN/Bodypaint-43.webp", "/models/LAUREN/Bodypaint-50.webp", "/models/LAUREN/Bodypaint-87.webp", "/models/LAUREN/Bodypaint-93.webp", "/models/LAUREN/Lauren-25.webp", "/models/LAUREN/Lauren-56.webp", "/models/LAUREN/Lauren-69.webp", "/models/LAUREN/Retouched-6.webp"] },
  { id:57,name:"LAUSHERN",type:"Director",img:"/models/LAUSHERN/Laushern-10.webp",loc:"Austin, TX",bio:"Building worlds one frame at a time.",collabs:26,score:90,verified:false,styles:["Vintage", "Editorial", "Abstract", "Fine Art"],looking:["Writer", "Videographer", "Producer"],connection:"mentor",nsfw:false,online:false,zodiac:"Libra",chinese:"Ox",mbti:"ISTP",lifePath:6,badges:[{name: "Local Legend", desc: "Top creative in their city", icon: "📍", color: "#87CEEB"}, {name: "Rising Star", desc: "New to Muse, gaining traction", icon: "✦", color: "#98FB98"}, {name: "Quick Responder", desc: "Responds within 2 hours", icon: "⚡", color: "#FFD700"}, {name: "Top Creator", desc: "80+ collaborations completed", icon: "★", color: "#FF8A80"}],photos:["/models/LAUSHERN/Laushern-10.webp", "/models/LAUSHERN/Laushern-103.webp", "/models/LAUSHERN/Laushern-24.webp", "/models/LAUSHERN/Laushern-32.webp", "/models/LAUSHERN/Laushern-40.webp", "/models/LAUSHERN/Laushern-46.webp", "/models/LAUSHERN/Laushern-6.webp", "/models/LAUSHERN/Laushern-68.webp", "/models/LAUSHERN/Laushern-72.webp", "/models/LAUSHERN/Laushern-77.webp"] },
  { id:58,name:"LORIE",type:"Producer",img:"/models/LORIE/IMG_1672.webp",loc:"New York, NY",bio:"Making creative chaos look effortless.",collabs:108,score:73,verified:true,styles:["Commercial", "Fashion", "Fine Art"],looking:["Musician", "Producer"],connection:"mentor",nsfw:false,online:true,zodiac:"Sagittarius",chinese:"Dragon",mbti:"ISTP",lifePath:8,badges:[{name: "Match Magnet", desc: "10+ matches this month", icon: "♥", color: "#FF69B4"}, {name: "Verified Pro", desc: "Identity verified by Muse", icon: "✓", color: "#FFD700"}, {name: "Rising Star", desc: "New to Muse, gaining traction", icon: "✦", color: "#98FB98"}, {name: "Top Creator", desc: "80+ collaborations completed", icon: "★", color: "#FF8A80"}],photos:["/models/LORIE/IMG_1672.webp", "/models/LORIE/IMG_1676.webp", "/models/LORIE/IMG_1678.webp", "/models/LORIE/IMG_1679.webp", "/models/LORIE/IMG_1681.webp", "/models/LORIE/IMG_1682.webp", "/models/LORIE/IMG_1684.webp", "/models/LORIE/IMG_1687.webp", "/models/LORIE/IMG_1689.webp", "/models/LORIE/IMG_1691.webp"] },
  { id:59,name:"MALIKA",type:"Editor",img:"/models/MALIKA/-3-15.webp",loc:"Miami, FL",bio:"Post-production specialist. VFX and color.",collabs:5,score:71,verified:true,styles:["Abstract", "Bold", "Editorial", "Vintage"],looking:["Videographer", "Writer", "Musician"],connection:"partner",nsfw:false,online:true,zodiac:"Gemini",chinese:"Rat",mbti:"ISTJ",lifePath:1,badges:[{name: "Match Magnet", desc: "10+ matches this month", icon: "♥", color: "#FF69B4"}, {name: "Style Icon", desc: "Recognized for outstanding style", icon: "✦", color: "#D4A5FF"}, {name: "Super Collab", desc: "High match compatibility", icon: "♥", color: "#FF69B4"}],photos:["/models/MALIKA/-3-15.webp", "/models/MALIKA/-3-18.webp", "/models/MALIKA/-3-7.webp", "/models/MALIKA/-3-8.webp", "/models/MALIKA/luv-127.webp", "/models/MALIKA/luv-139.webp", "/models/MALIKA/luv-184.webp", "/models/MALIKA/luv-190.webp", "/models/MALIKA/luv-224.webp", "/models/MALIKA/luv-240.webp"] },
  { id:60,name:"MAYA",type:"Model",img:"/models/MAYA/Maya-28.webp",loc:"Los Angeles, CA",bio:"Editorial and commercial model with a love for cinematic storytelling.",collabs:42,score:82,verified:true,styles:["Fashion","Editorial","Portrait"],looking:["Photographer","Director"],connection:"collab",nsfw:false,online:true,zodiac:"Pisces",chinese:"Rabbit",mbti:"ENFP",lifePath:3,badges:[{name:"Verified Pro",desc:"Identity verified by Muse",icon:"✓",color:"#FFD700"}],prompts:[{q:"My creative superpower is",a:"Finding beauty in chaos"},{q:"My dream project",a:"A 40-page Vogue editorial"}],photos:["/models/MAYA/Maya-28.webp","/models/MAYA/Maya-30.webp","/models/MAYA/Maya-31.webp","/models/MAYA/Maya-32.webp","/models/MAYA/Maya-33.webp","/models/MAYA/Maya-34.webp","/models/MAYA/Maya-35.webp","/models/MAYA/Maya-36.webp","/models/MAYA/Maya-39.webp","/models/MAYA/Maya-41.webp"] },
  { id:61,name:"MITRI",type:"Producer",img:"/models/MITRI/Mitri-10.webp",loc:"Las Vegas, NV",bio:"Project visionary and team builder.",collabs:106,score:90,verified:true,styles:["Film", "Dark"],looking:["Producer", "Writer"],connection:"partner",nsfw:false,online:true,zodiac:"Aquarius",chinese:"Horse",mbti:"ISFJ",lifePath:11,badges:[{name: "Quick Responder", desc: "Responds within 2 hours", icon: "⚡", color: "#FFD700"}, {name: "Local Legend", desc: "Top creative in their city", icon: "📍", color: "#87CEEB"}, {name: "Top Creator", desc: "80+ collaborations completed", icon: "★", color: "#FF8A80"}, {name: "Creative Sage", desc: "47+ collaborations completed", icon: "◊", color: "#FFB5C2"}],photos:["/models/MITRI/Mitri-10.webp", "/models/MITRI/Mitri-100.webp", "/models/MITRI/Mitri-101.webp", "/models/MITRI/Mitri-102.webp", "/models/MITRI/Mitri-103.webp", "/models/MITRI/Mitri-104.webp", "/models/MITRI/Mitri-107.webp", "/models/MITRI/Mitri-11.webp", "/models/MITRI/Mitri-110.webp", "/models/MITRI/Mitri-111.webp"] },
  { id:62,name:"NAKIA",type:"Videographer",img:"/models/NAKIA/Nakia-10.webp",loc:"Seattle, WA",bio:"Capturing motion and emotion.",collabs:75,score:92,verified:true,styles:["Experimental", "Documentary", "Portrait"],looking:["Designer", "Editor", "Producer"],connection:"friend",nsfw:false,online:true,zodiac:"Virgo",chinese:"Goat",mbti:"ESFP",lifePath:7,badges:[{name: "Super Collab", desc: "High match compatibility", icon: "♥", color: "#FF69B4"}, {name: "Top Creator", desc: "80+ collaborations completed", icon: "★", color: "#FF8A80"}],photos:["/models/NAKIA/Nakia-10.webp", "/models/NAKIA/Nakia-100.webp", "/models/NAKIA/Nakia-101.webp", "/models/NAKIA/Nakia-102.webp", "/models/NAKIA/Nakia-106.webp", "/models/NAKIA/Nakia-109.webp", "/models/NAKIA/Nakia-111.webp", "/models/NAKIA/Nakia-114.webp", "/models/NAKIA/Nakia-115.webp", "/models/NAKIA/Nakia-117.webp"] },
  { id:63,name:"NICO  +  DRACO",type:"Videographer",img:"/models/NICO__plus__DRACO/Nico + Draco-105.webp",loc:"Nashville, TN",bio:"Drone cinematography and landscape films.",collabs:76,score:74,verified:true,styles:["Bold", "Experimental", "Fashion", "Documentary"],looking:["Writer", "Editor"],connection:"collab",nsfw:false,online:true,zodiac:"Taurus",chinese:"Horse",mbti:"ENFP",lifePath:7,badges:[{name: "Super Collab", desc: "High match compatibility", icon: "♥", color: "#FF69B4"}, {name: "Match Magnet", desc: "10+ matches this month", icon: "♥", color: "#FF69B4"}],photos:["/models/NICO__plus__DRACO/Nico + Draco-105.webp", "/models/NICO__plus__DRACO/Nico + Draco-24.webp", "/models/NICO__plus__DRACO/Nico + Draco-30.webp", "/models/NICO__plus__DRACO/Nico + Draco-41.webp", "/models/NICO__plus__DRACO/Nico + Draco-50.webp", "/models/NICO__plus__DRACO/Nico + Draco-84.webp", "/models/NICO__plus__DRACO/Nico + Draco-89.webp", "/models/NICO__plus__DRACO/Nico + Draco-91.webp", "/models/NICO__plus__DRACO/Nico + Draco-93.webp", "/models/NICO__plus__DRACO/Nico + Draco-96.webp"] },
  { id:64,name:"NIYAH",type:"Designer",img:"/models/NIYAH/Niya-12.webp",loc:"Portland, OR",bio:"Visual problem solver.",collabs:81,score:95,verified:false,styles:["Branding", "Commercial"],looking:["Videographer", "Director", "Designer"],connection:"collab",nsfw:false,online:true,zodiac:"Leo",chinese:"Ox",mbti:"ISTJ",lifePath:7,badges:[{name: "Quick Responder", desc: "Responds within 2 hours", icon: "⚡", color: "#FFD700"}, {name: "Creative Sage", desc: "47+ collaborations completed", icon: "◊", color: "#FFB5C2"}, {name: "Rising Star", desc: "New to Muse, gaining traction", icon: "✦", color: "#98FB98"}],photos:["/models/NIYAH/Niya-12.webp", "/models/NIYAH/Niya-14.webp", "/models/NIYAH/Niya-15.webp", "/models/NIYAH/Niya-17.webp", "/models/NIYAH/Niya-23.webp", "/models/NIYAH/Niya-24.webp", "/models/NIYAH/Niya-33.webp", "/models/NIYAH/Niya-35.webp", "/models/NIYAH/Niya-4.webp", "/models/NIYAH/Niya-41.webp"] },
  { id:65,name:"ODU",type:"Designer",img:"/models/ODU/Label Me-40.webp",loc:"Las Vegas, NV",bio:"Visual problem solver.",collabs:74,score:75,verified:true,styles:["Abstract", "Music Video", "Commercial", "Editorial"],looking:["Producer", "Writer", "Photographer"],connection:"partner",nsfw:false,online:true,zodiac:"Taurus",chinese:"Pig",mbti:"ENFJ",lifePath:1,badges:[{name: "Match Magnet", desc: "10+ matches this month", icon: "♥", color: "#FF69B4"}, {name: "Super Collab", desc: "High match compatibility", icon: "♥", color: "#FF69B4"}, {name: "Verified Pro", desc: "Identity verified by Muse", icon: "✓", color: "#FFD700"}],photos:["/models/ODU/Label Me-40.webp", "/models/ODU/Label Me-44.webp", "/models/ODU/Label Me-5.webp", "/models/ODU/Label Me-7.webp", "/models/ODU/Odu-13.webp", "/models/ODU/Odu-18.webp", "/models/ODU/Odu-23.webp", "/models/ODU/Odu-30.webp", "/models/ODU/Odu-50.webp", "/models/ODU/Odu-7.webp"] },
  { id:66,name:"PRADIA",type:"Model",img:"/models/PRADIA/Pradia-10.webp",loc:"Miami, FL",bio:"Between the lines of fashion and art.",collabs:55,score:82,verified:true,styles:["Branding", "Abstract", "Editorial", "Experimental"],looking:["Producer", "Videographer", "Musician"],connection:"friend",nsfw:false,online:false,zodiac:"Libra",chinese:"Snake",mbti:"ENTP",lifePath:5,badges:[{name: "Local Legend", desc: "Top creative in their city", icon: "📍", color: "#87CEEB"}, {name: "Top Creator", desc: "80+ collaborations completed", icon: "★", color: "#FF8A80"}, {name: "Super Collab", desc: "High match compatibility", icon: "♥", color: "#FF69B4"}],photos:["/models/PRADIA/Pradia-10.webp", "/models/PRADIA/Pradia-12.webp", "/models/PRADIA/Pradia-14.webp", "/models/PRADIA/Pradia-16.webp", "/models/PRADIA/Pradia-22.webp", "/models/PRADIA/Pradia-26.webp", "/models/PRADIA/Pradia-29.webp", "/models/PRADIA/Pradia-30.webp", "/models/PRADIA/Pradia-33.webp", "/models/PRADIA/Pradia-39.webp"] },
  { id:67,name:"QUANISHA",type:"Content Creator",img:"/models/QUANISHA/Quanisha-11.webp",loc:"Atlanta, GA",bio:"Turning ideas into viral moments.",collabs:89,score:78,verified:false,styles:["Body Art", "Vintage", "Branding", "Commercial"],looking:["Photographer", "Writer", "Musician"],connection:"partner",nsfw:false,online:false,zodiac:"Capricorn",chinese:"Snake",mbti:"ENTP",lifePath:9,badges:[{name: "Rising Star", desc: "New to Muse, gaining traction", icon: "✦", color: "#98FB98"}, {name: "Style Icon", desc: "Recognized for outstanding style", icon: "✦", color: "#D4A5FF"}, {name: "Creative Sage", desc: "47+ collaborations completed", icon: "◊", color: "#FFB5C2"}],photos:["/models/QUANISHA/Quanisha-11.webp", "/models/QUANISHA/Quanisha-110.webp", "/models/QUANISHA/Quanisha-177.webp", "/models/QUANISHA/Quanisha-25.webp", "/models/QUANISHA/Quanisha-26.webp", "/models/QUANISHA/Quanisha-43.webp", "/models/QUANISHA/Quanisha-48.webp", "/models/QUANISHA/Quanisha-65.webp", "/models/QUANISHA/Quanisha-70.webp", "/models/QUANISHA/Retouched-16.webp"] },
  { id:68,name:"RANISHA",type:"Actor",img:"/models/RANISHA/NISHA-16.webp",loc:"New York, NY",bio:"Character-driven performer.",collabs:84,score:73,verified:true,styles:["Dark", "Vintage", "Body Art"],looking:["Musician", "Photographer"],connection:"mentor",nsfw:false,online:false,zodiac:"Virgo",chinese:"Rat",mbti:"ISTP",lifePath:5,badges:[{name: "Rising Star", desc: "New to Muse, gaining traction", icon: "✦", color: "#98FB98"}, {name: "Super Collab", desc: "High match compatibility", icon: "♥", color: "#FF69B4"}, {name: "Verified Pro", desc: "Identity verified by Muse", icon: "✓", color: "#FFD700"}, {name: "Creative Sage", desc: "47+ collaborations completed", icon: "◊", color: "#FFB5C2"}],photos:["/models/RANISHA/NISHA-16.webp", "/models/RANISHA/NISHA-36.webp", "/models/RANISHA/NISHA-41.webp", "/models/RANISHA/NISHA-44.webp", "/models/RANISHA/NISHA-47.webp", "/models/RANISHA/NISHA-54.webp", "/models/RANISHA/NISHA-66.webp", "/models/RANISHA/NISHA-8.webp", "/models/RANISHA/NISHA-85.webp", "/models/RANISHA/NISHA-8_1.webp"] },
  { id:69,name:"REBECCA",type:"Videographer",img:"/models/REBECCA/REBECCA-13.webp",loc:"Chicago, IL",bio:"Drone cinematography and landscape films.",collabs:113,score:92,verified:true,styles:["Experimental", "Editorial", "Commercial"],looking:["Producer", "Editor", "Designer"],connection:"partner",nsfw:false,online:false,zodiac:"Taurus",chinese:"Tiger",mbti:"ENFP",lifePath:1,badges:[{name: "Local Legend", desc: "Top creative in their city", icon: "📍", color: "#87CEEB"}, {name: "Top Creator", desc: "80+ collaborations completed", icon: "★", color: "#FF8A80"}, {name: "Creative Sage", desc: "47+ collaborations completed", icon: "◊", color: "#FFB5C2"}],photos:["/models/REBECCA/REBECCA-13.webp", "/models/REBECCA/REBECCA-136.webp", "/models/REBECCA/REBECCA-215.webp", "/models/REBECCA/REBECCA-217.webp", "/models/REBECCA/REBECCA-269.webp", "/models/REBECCA/REBECCA-274.webp", "/models/REBECCA/REBECCA-275.webp", "/models/REBECCA/REBECCA-35.webp", "/models/REBECCA/REBECCA-7.webp", "/models/REBECCA/Retouched-14.webp"] },
  { id:70,name:"ROY",type:"Actor",img:"/models/ROY/Roy-10.webp",loc:"Las Vegas, NV",bio:"Bringing authenticity to every role.",collabs:42,score:89,verified:false,styles:["Commercial", "Editorial", "Abstract"],looking:["Producer", "Designer", "Editor"],connection:"collab",nsfw:false,online:false,zodiac:"Aries",chinese:"Horse",mbti:"ENFP",lifePath:5,badges:[{name: "Match Magnet", desc: "10+ matches this month", icon: "♥", color: "#FF69B4"}, {name: "Top Creator", desc: "80+ collaborations completed", icon: "★", color: "#FF8A80"}, {name: "Rising Star", desc: "New to Muse, gaining traction", icon: "✦", color: "#98FB98"}, {name: "Local Legend", desc: "Top creative in their city", icon: "📍", color: "#87CEEB"}],photos:["/models/ROY/Roy-10.webp", "/models/ROY/Roy-25.webp", "/models/ROY/Roy-3.webp", "/models/ROY/Roy-33.webp", "/models/ROY/Roy-39.webp", "/models/ROY/Roy-4.webp", "/models/ROY/Roy-40.webp", "/models/ROY/Roy-45.webp", "/models/ROY/Roy-47.webp", "/models/ROY/Roy-59.webp"] },
  { id:71,name:"SIMONE",type:"Producer",img:"/models/SIMONE/Simone-107.webp",loc:"Austin, TX",bio:"Project visionary and team builder.",collabs:81,score:73,verified:true,styles:["Portrait", "Abstract"],looking:["Editor", "Director", "Videographer"],connection:"friend",nsfw:false,online:true,zodiac:"Aries",chinese:"Dragon",mbti:"ENFJ",lifePath:4,badges:[{name: "Quick Responder", desc: "Responds within 2 hours", icon: "⚡", color: "#FFD700"}, {name: "Creative Sage", desc: "47+ collaborations completed", icon: "◊", color: "#FFB5C2"}, {name: "Rising Star", desc: "New to Muse, gaining traction", icon: "✦", color: "#98FB98"}, {name: "Verified Pro", desc: "Identity verified by Muse", icon: "✓", color: "#FFD700"}],photos:["/models/SIMONE/Simone-107.webp", "/models/SIMONE/Simone-119.webp", "/models/SIMONE/Simone-130.webp", "/models/SIMONE/Simone-135.webp", "/models/SIMONE/Simone-138.webp", "/models/SIMONE/Simone-14 (1).webp", "/models/SIMONE/Simone-158.webp", "/models/SIMONE/Simone-163.webp", "/models/SIMONE/Simone-17 (1).webp", "/models/SIMONE/Simone-20.webp"] },
];

export const BRIEFS = [
  { id:1,title:"Album Artwork Collection",author:"Luna Martinez",authorImg:"https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=80&h=80&fit=crop",budget:"$2,000-$3,000",deadline:"4 weeks",desc:"Need a series of 8 album covers for an electronic music EP. Dark, ethereal, neon-noir aesthetic.",tags:["Album Art","Digital Art","Dark"],applicants:12,urgent:true,cat:"paid" },
  { id:2,title:"Fashion Campaign Video",author:"Noah Bennett",authorImg:"https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=80&h=80&fit=crop",budget:"$5,000-$8,000",deadline:"6 weeks",desc:"Spring/summer campaign for an indie fashion label. Need a creative videographer with editorial experience.",tags:["Fashion","Video","Campaign"],applicants:8,urgent:false,cat:"paid" },
  { id:3,title:"Studio Space Mural",author:"Aria Patel",authorImg:"https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=80&h=80&fit=crop",budget:"$1,500-$2,500",deadline:"2 weeks",desc:"Looking for a mural artist to transform our photography studio into a dreamscape.",tags:["Mural","Installation","Dream"],applicants:5,urgent:true,cat:"paid" },
  { id:4,title:"Figure Art Collaboration",author:"Dante Black",authorImg:"https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&h=80&fit=crop",budget:"TFP",deadline:"Open",desc:"Seeking fine art photographers for a body-positive series exploring light and shadow on the human form.",tags:["Fine Art","Figure","Body"],applicants:7,urgent:false,nsfw:true,cat:"tfp" },
  { id:5,title:"Music Video Production",author:"Maya Singh",authorImg:"https://images.unsplash.com/photo-1517841905240-472988babdf9?w=80&h=80&fit=crop",budget:"$3,000-$5,000",deadline:"3 weeks",desc:"Indie artist needs a director and DP for a dream-pop music video. Story-driven, ethereal visuals.",tags:["Music Video","Story","Dream Pop"],applicants:3,urgent:false,cat:"paid" },
  { id:6,title:"Brand Photo Package",author:"Kai Yamamoto",authorImg:"https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=80&h=80&fit=crop",budget:"$800-$1,500",deadline:"1 week",desc:"Small business needs professional product and lifestyle photos for website and social media.",tags:["Product","Lifestyle","Brand"],applicants:4,urgent:false,cat:"paid" },
  { id:7,title:"Sunset Beach Shoot - TFP",author:"Zara Kim",authorImg:"https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=80&h=80&fit=crop",budget:"TFP",deadline:"This Saturday",desc:"Looking for a model and MUA for golden hour beach shoot. Editorial/fashion vibes. TFP - everyone gets shots.",tags:["TFP","Editorial","Beach"],applicants:6,urgent:false,cat:"tfp" },
  { id:8,title:"Documentary Short - Open Call",author:"Leo Torres",authorImg:"https://images.unsplash.com/photo-1463453091185-61582044d556?w=80&h=80&fit=crop",budget:"Volunteer",deadline:"Rolling",desc:"Looking for crew for a documentary about LA's underground art scene. Passion project, no budget but great exposure.",tags:["Documentary","Art","Community"],applicants:15,urgent:false,cat:"opencall" },
  { id:9,title:"Anyone want to shoot something this weekend?",author:"Mia Johnson",authorImg:"https://images.unsplash.com/photo-1517841905240-472988babdf9?w=80&h=80&fit=crop",budget:"—",deadline:"Weekend",desc:"Got a free weekend and want to create something. No plan yet, just vibes. DM if you're down to vision ideas.",tags:["Casual","Weekend","Ideas"],applicants:9,urgent:false,cat:"concept" },
  { id:10,title:"Collab idea: neon noir photo series",author:"Remy Zhang",authorImg:"https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=80&h=80&fit=crop",budget:"—",deadline:"Flexible",desc:"Been thinking about a neon noir series - think Blade Runner meets Wong Kar-wai. Need a DP and stylist who's into it.",tags:["Concept","Neon Noir","Photo"],applicants:4,urgent:false,cat:"concept" },
];

export const COMMUNITIES = [
  {id:1,name:"LA Photographers",img:"https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100",members:"12.4k",desc:"SoCal's biggest photo community",cat:"photo",nsfw:false},
  {id:2,name:"Queer Creatives United",img:"https://images.unsplash.com/photo-1517841905240-472988babdf9?w=100",members:"8.2k",desc:"Safe space for LGBTQIA+ artists",cat:"social",nsfw:false},
  {id:3,name:"Figure Art Collective",img:"https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100",members:"4.7k",desc:"Body-positive fine art & figure photography",cat:"nsfw",nsfw:true},
  {id:4,name:"Film & Video Directors",img:"https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100",members:"6.1k",desc:"For directors and visual storytellers",cat:"photo",nsfw:false},
  {id:5,name:"MUA & Stylist Network",img:"https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100",members:"3.9k",desc:"Beauty & fashion industry pros",cat:"social",nsfw:false},
  {id:6,name:"Indie Film Collective",img:"https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=100",members:"5.6k",desc:"Independent filmmakers sharing resources and collabs",cat:"film",nsfw:false},
  {id:7,name:"Digital Artists Guild",img:"https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop",members:"7.3k",desc:"CGI, 3D, and digital art enthusiasts",cat:"design",nsfw:false},
  {id:8,name:"Street Photography NYC",img:"https://images.unsplash.com/photo-1531913764164-f85c3e03b2aa?w=100",members:"3.1k",desc:"Urban photography collective for NYC creatives",cat:"photo",nsfw:false},
  {id:9,name:"Women in Film & TV",img:"https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=100",members:"9.4k",desc:"Supporting women and non-binary creatives in media",cat:"social",nsfw:false},
  {id:10,name:"Body Positive Artists",img:"https://images.unsplash.com/photo-1473186505569-9c61870c11f9?w=100",members:"2.8k",desc:"Safe space for figure and body-positive art",cat:"nsfw",nsfw:true},
  {id:11,name:"Music Video Directors",img:"https://images.unsplash.com/photo-1515187029135-18ee286d815b?w=100",members:"4.2k",desc:"Directors, DPs, and VJs for music visual storytelling",cat:"film",nsfw:false},
  {id:12,name:"Fashion Photographers Hub",img:"https://images.unsplash.com/photo-1523050854058-8df90110c7f1?w=100",members:"6.7k",desc:"Commercial and editorial fashion photography",cat:"photo",nsfw:false},];

export const EVENTS = [
  {id:1,title:"Golden Hour Meetup",date:"Sat, Jul 20",loc:"Venice Beach",desc:"Group shoot at sunset. All levels welcome.",nsfw:false},
  {id:2,title:"Creative Portfolio Review",date:"Wed, Jul 24",loc:"Online (Zoom)",desc:"Get feedback from industry pros on your portfolio.",nsfw:false},
  {id:3,title:"Street Style Workshop",date:"Sat, Aug 3",loc:"Downtown LA",desc:"Learn candid street photography techniques.",nsfw:false},
  {id:4,title:"Figure Art Exhibition",date:"Fri, Aug 9",loc:"Arts District",desc:"Annual body-positive fine art show.",nsfw:false},
  {id:5,title:"Film Scoring 101",date:"Sun, Aug 18",loc:"Online (Zoom)",desc:"Compose for visual media.",nsfw:false},
  {id:6,title:"Mobile Photography Masterclass",date:"Tue, Aug 22",loc:"Santa Monica Pier",desc:"Shoot and edit pro-level mobile photos on your iPhone.",nsfw:false},
  {id:7,title:"Neon Night Shoot",date:"Fri, Aug 30",loc:"Downtown LA",desc:"After-dark urban portrait session with neon lighting.",nsfw:false},
  {id:8,title:"Body Positive Figure Workshop",date:"Sat, Sep 7",loc:"Culver City Studio",desc:"Life drawing and photography workshop for all genders.",nsfw:true},
  {id:9,title:"VR Cinematography Lab",date:"Mon, Sep 16",loc:"Virtual Reality LA",desc:"Experiment with VR filmmaking tools and techniques.",nsfw:false},
  {id:10,title:"Indie Film Pitch Night",date:"Thu, Sep 26",loc:"The Standard, Downtown LA",desc:"Pitch your project to producers and distributors.",nsfw:false},
];

export const SESSIONS = [
  {id:201,name:"Maya Chen",type:"Photographer",img:"https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200",rate:"$75/hr",rating:4.9,sessions:128,available:true,skills:["Portrait","Fashion","Editorial"]},
  {id:202,name:"Jordan Rivera",type:"Director",img:"https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200",rate:"$120/hr",rating:4.8,sessions:89,available:true,skills:["Music Video","Commercial","Short Film"]},
  {id:203,name:"Alex Kim",type:"Editor",img:"https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200",rate:"$60/hr",rating:4.7,sessions:201,available:false,skills:["Color Grading","VFX","Sound Design"]},
  {id:204,name:"Sam Taylor",type:"Composer",img:"https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200",rate:"$90/hr",rating:4.9,sessions:156,available:true,skills:["Score","Production","Mixing"]},
  {id:205,name:"Riley Patel",type:"Designer",img:"https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200",rate:"$85/hr",rating:4.6,sessions:94,available:true,skills:["Brand","UI/UX","Motion"]},
];

export const FORUM_POSTS = [
  {id:301,title:"Best lighting setup for outdoor portraits?",body:"I've been struggling with harsh shadows during midday shoots. What modifiers do you swear by?",author:"Maya Chen",avatar:"https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100",votes:47,comments:[{author:"Jordan R.",text:"Reflector + fill flash combo. Game changer."},{author:"Alex K.",text:"Overcast days or golden hour."}],cat:"Photography",time:"2h ago",pinned:true},
  {id:302,title:"How do you price music video production?",body:"I'm getting more requests but have no idea what the market rate is in LA.",author:"Jordan Rivera",avatar:"https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100",votes:32,comments:[{author:"Sam T.",text:"$5K-25K for indie."}],cat:"Business",time:"5h ago",pinned:false},
  {id:303,title:"DaVinci Resolve vs Premiere - 2026 edition",body:"Switched to Resolve last year. The color grading tools are unmatched.",author:"Alex Kim",avatar:"https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100",votes:89,comments:[{author:"Maya C.",text:"Resolve for color, Premiere for everything else."}],cat:"Editing",time:"1d ago",pinned:false},
  {id:304,title:"Looking for a videographer for short film",body:"Shooting a 15-min neo-noir short in August. Paid gig.",author:"Sam Taylor",avatar:"https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100",votes:23,comments:[],cat:"Collab",time:"3h ago",pinned:false},
  {id:305,title:"Portfolio website: Squarespace vs custom Next.js?",body:"My Squarespace site feels generic. Is custom worth it?",author:"Riley Patel",avatar:"https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100",votes:56,comments:[{author:"Alex K.",text:"Custom all the way."}],cat:"Career",time:"8h ago",pinned:false},
  {id:306,title:"What's your backup workflow?",body:"How do you ensure you never lose footage? Looking for redundant strategies.",author:"Elena Voss",avatar:"https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100",votes:41,comments:[{author:"Sam T.","text":"Dual cards + 3-2-1 backup rule."},{author:"Alex K.","text":"Cloud sync to Backblaze."}],cat:"Tech",time:"12h ago",pinned:false},
  {id:307,title:"Canon C70 vs Sony FX6 - real world comparison",body:"Used both on a recent commercial shoot. Here's what I learned.",author:"Jordan Rivera",avatar:"https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100",votes:78,comments:[],cat:"Gear",time:"2d ago",pinned:false},
  {id:308,title:"How to get your first paid client",body:"New creator here. How did you land your first paying project?",author:"Maya Chen",avatar:"https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100",votes:102,comments:[{author:"Riley P.","text":"Build a strong personal project first."},{author:"Sam T.","text":"Network locally, not online."}],cat:"Career",time:"3d ago",pinned:true},
  {id:309,title:"AI tools for color grading - legit or cringe?",body:"Seeing more AI tools pop up. Are they actually useful for professionals?",author:"Alex Kim",avatar:"https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100",votes:36,comments:[],cat:"Tech",time:"4h ago",pinned:false},
  {id:310,title:"Collab wanted: fashion photographer + dancer",body:"Looking to create a movement-based editorial series. TFP or low budget.",author:"Sam Taylor",avatar:"https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100",votes:18,comments:[],cat:"Collab",time:"6h ago",pinned:false},
];

export const TIERS = [
  { name:"Free",price:"$0",period:"forever",features:["10 likes/day","Basic profile","Chat with matches","Standard discover"],current:true },
  { name:"Muse Pro",price:"$9.99",period:"/month",features:["Unlimited likes","See who likes you","Advanced filters","Read receipts","Profile boost (x1/week)","Incognito mode","Priority discover"] },
];

export const AESTHETICS = ["Portrait","Editorial","Commercial","Music Video","Documentary","Branding","Body Art","Fine Art","Fashion","Experimental","Dark","Dreamy","Bold","Vintage","Abstract","Film"];
export const CREATIVE_TYPES = ["Photographer","Model","Content Creator","Director","Editor","MUA","Stylist","Actor","Videographer","Writer","Producer","Designer"];
export const LOOKING_FOR = ["Photographer","Videographer","Director","Editor","Musician","Writer","Designer","Producer"];
export const CONN_TYPES = ["friend","collab","mentor","partner"];
export const ZODIAC = ["Aries","Taurus","Gemini","Cancer","Leo","Virgo","Libra","Scorpio","Sagittarius","Capricorn","Aquarius","Pisces"];
export const ZE:Record<string,string> = {"Aries":"🔥 Bold pioneer","Taurus":"🌍 Grounded sensualist","Gemini":"💨 Curious connector","Cancer":"💧 Empathetic soul","Leo":"🔥 Creative star","Virgo":"🌍 Meticulous artisan","Libra":"💨 Balanced visionary","Scorpio":"💧 Intense transformer","Sagittarius":"🔥 Adventurous spirit","Capricorn":"🌍 Ambitious builder","Aquarius":"💨 Future thinker","Pisces":"💧 Dreamy mystic"};
export const CHINESE = ["Rat","Ox","Tiger","Rabbit","Dragon","Snake","Horse","Goat","Monkey","Rooster","Dog","Pig"];
export const CE:Record<string,string> = {"Rat":"🐀 Quick-witted","Ox":"🐂 Steadfast","Tiger":"🐅 Courageous","Rabbit":"🐇 Graceful","Dragon":"🐉 Charismatic","Snake":"🐍 Wise","Horse":"🐴 Energetic","Goat":"🐐 Creative","Monkey":"🐒 Clever","Rooster":"🐓 Confident","Dog":"🐕 Loyal","Pig":"🐖 Generous"};
export const MBTI = ["INTJ","INTP","ENTJ","ENTP","INFJ","INFP","ENFJ","ENFP","ISTJ","ISFJ","ESTJ","ESFJ","ISTP","ISFP","ESTP","ESFP"];
export const LIFE_PATHS = [1,2,3,4,5,6,7,8,9,11,22,33];
export const PC = ["#FFD700","#FF6B6B","#D4A5FF","#98FB98","#FFDAB9","#87CEEB","#FF8A80","#FFD1A4","#FFB5C2","#FFE4B5","#FF9A56","#E6E6FA"];
export const PROFESSIONALS = [
  {id:1,name:"Elena Voss",type:"Casting Director",img:"https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200",loc:"Los Angeles, CA",exp:"8 years",openings:3,skills:["Fashion","Commercial","Editorial"],nsfw:false},
  {id:2,name:"Marcus Webb",type:"Producer",img:"https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200",loc:"New York, NY",exp:"12 years",openings:5,skills:["Music Video","Commercial","Film"],nsfw:false},
  {id:3,name:"Simone Hart",type:"Art Buyer",img:"https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200",loc:"San Francisco, CA",exp:"6 years",openings:2,skills:["Fine Art","Fashion","Editorial"],nsfw:false},
  {id:4,name:"Dante Cruz",type:"Fine Art Agent",img:"https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200",loc:"Miami, FL",exp:"10 years",openings:7,skills:["Body Art","Fine Art","Fashion"],nsfw:true},
  {id:5,name:"Lena Park",type:"Creative Director",img:"https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200",loc:"Austin, TX",exp:"15 years",openings:4,skills:["Branding","Commercial","Experimental"],nsfw:false},
];
export const CONNECTIONS = [
  { name:"Creative Mornings LA",type:"Community",cat:"community",img:"https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=200&h=120&fit=crop",desc:"Weekly creative networking events in LA",tag:"Events" },
  { name:"AFI Conservatory",type:"Film School",cat:"education",img:"https://images.unsplash.com/photo-1523050854058-8df90110c7f1?w=200&h=120&fit=crop",desc:"American Film Institute alumni network",tag:"Film" },
  { name:"LA Art Walk",type:"Community",cat:"community",img:"https://images.unsplash.com/photo-1531913764164-f85c3e03b2aa?w=200&h=120&fit=crop",desc:"Downtown LA monthly artwalk collective",tag:"Art" },
  { name:"The Muse Agency",type:"Talent",cat:"talent",img:"https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=200&h=120&fit=crop",desc:"Creative talent matching platform",tag:"Matching" },
  { name:"Sundance Collab",type:"Workshop",cat:"education",img:"https://images.unsplash.com/photo-1515187029135-18ee286d815b?w=200&h=120&fit=crop",desc:"Filmmaker workshops and labs",tag:"Education" },
  { name:"Figure Art Creatives United",type:"Community",cat:"nsfw",img:"https://images.unsplash.com/photo-1519741497674-611481863552?w=200&h=120&fit=crop",desc:"Safe space for fine art figure & body-positive creatives",tag:"Figure Art" },
  { name:"FotoFest",type:"Exhibition",cat:"community",img:"https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=200&h=120&fit=crop",desc:"Fine art photography biennial",tag:"Photo" },
  { name:"Stage 32",type:"Network",cat:"talent",img:"https://images.unsplash.com/photo-1516245834210-c4c142787335?w=200&h=120&fit=crop",desc:"Film & TV industry networking platform",tag:"Film" },
  { name:"Body Art Collective",type:"Community",cat:"nsfw",img:"https://images.unsplash.com/photo-1473186505569-9c61870c11f9?w=200&h=120&fit=crop",desc:"Fine art body photography collective",tag:"Figure Art" },
  { name:"Smashbox Studios",type:"Studio",cat:"talent",img:"https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=200&h=120&fit=crop",desc:"Iconic LA photo and film studio",tag:"Studio" },
  { name:"Women in Film",type:"Community",cat:"community",img:"https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=200&h=120&fit=crop",desc:"Supporting women in the film industry",tag:"Film" },
  { name:"Prism Studio",type:"Studio",cat:"nsfw",img:"https://images.unsplash.com/photo-1520975916090-3105956dac38?w=200&h=120&fit=crop",desc:"Inclusive studio for body-positive fine art",tag:"Figure Art" },
];

export function calcMatch(a: { styles: string[]; looking: string[]; zodiac?: string; chinese?: string; mbti?: string; lifePath?: number }, b: typeof PROFILES[number]): number {
  let s = 40;
  const shared = a.styles.filter(x => b.styles.includes(x));
  s += Math.min(shared.length * 7, 21);
  if (a.looking.some(l => b.looking.some(bl => bl.toLowerCase().includes(l.toLowerCase()) || l.toLowerCase().includes(bl.toLowerCase())))) s += 15;
  if (a.looking.some(l => b.type.toLowerCase().includes(l.toLowerCase()))) s += 8;
  const zCompat: Record<string, string[]> = {"Aries":["Leo","Sagittarius","Gemini","Aquarius"],"Taurus":["Virgo","Capricorn","Cancer","Pisces"],"Gemini":["Libra","Aquarius","Aries","Leo"],"Cancer":["Scorpio","Pisces","Taurus","Virgo"],"Leo":["Aries","Sagittarius","Gemini","Libra"],"Virgo":["Taurus","Capricorn","Cancer","Scorpio"],"Libra":["Gemini","Aquarius","Aries","Sagittarius"],"Scorpio":["Cancer","Pisces","Taurus","Capricorn"],"Sagittarius":["Aries","Leo","Gemini","Libra"],"Capricorn":["Taurus","Virgo","Cancer","Scorpio"],"Aquarius":["Gemini","Libra","Aries","Sagittarius"],"Pisces":["Cancer","Scorpio","Taurus","Virgo"]};
  if (a.zodiac && b.zodiac) { if (a.zodiac === b.zodiac) s += 6; else if (zCompat[a.zodiac]?.includes(b.zodiac)) s += 4; }
  if (a.chinese && b.chinese && a.chinese === b.chinese) s += 6;
  const mCompat: Record<string, string[]> = {"INTJ":["ENTP","ENFP"],"INTP":["ENTJ","ENFJ"],"ENTJ":["INTP","INFP"],"ENTP":["INTJ","INFJ"],"INFJ":["ENFP","ENTP"],"INFP":["ENFJ","ENTJ"],"ENFJ":["INFP","INTP"],"ENFP":["INFJ","INTJ"],"ISTJ":["ESFP","ESTP"],"ISFJ":["ESFP","ESTP"],"ESTJ":["ISFP","ISTP"],"ESFJ":["ISFP","ISTP"],"ISTP":["ESFJ","ESTJ"],"ISFP":["ESFJ","ESTJ"],"ESTP":["ISTJ","ISFJ"],"ESFP":["ISTJ","ISFJ"]};
  if (a.mbti && b.mbti) { if (a.mbti === b.mbti) s += 5; else if (mCompat[a.mbti]?.includes(b.mbti)) s += 4; }
  if (a.lifePath && b.lifePath && a.lifePath === b.lifePath) s += 5;
  if (b.verified) s += 3;
  if (b.collabs > 50) s += 2;
  return Math.min(s, 99);
}

export function calcZodiac(month: number, day: number): string {
  const signs = ["Capricorn","Aquarius","Pisces","Aries","Taurus","Gemini","Cancer","Leo","Virgo","Libra","Scorpio","Sagittarius"];
  const cutoffs = [20,19,21,20,21,21,23,23,23,23,22,22];
  return day < cutoffs[month - 1] ? signs[(month + 10) % 12] : signs[(month + 11) % 12];
}

export function calcChineseZodiac(year: number): string {
  const animals = ["Rat","Ox","Tiger","Rabbit","Dragon","Snake","Horse","Goat","Monkey","Rooster","Dog","Pig"];
  return animals[(year - 1900) % 12];
}

export function calcLifePath(month: number, day: number, year: number): number {
  const sum = (n: number): number => { let s = 0; while (n > 0) { s += n % 10; n = Math.floor(n / 10); } return s > 9 ? sum(s) : s; };
  const lp = sum(month) + sum(day) + sum(year);
  return lp > 9 && lp !== 11 && lp !== 22 && lp !== 33 ? sum(lp) : lp;
}

export function calcMbti(answers: Record<string, string>): string {
  const e = (answers.ei || "e") === "e" ? "E" : "I";
  const s = (answers.sn || "s") === "s" ? "S" : "N";
  const t = (answers.tf || "t") === "t" ? "T" : "F";
  const j = (answers.jp || "j") === "j" ? "J" : "P";
  return e + s + t + j;
}

export const ICEBREAKERS: Record<string, string[]> = {
  Photographer: ["What's your favorite golden hour spot?", "Film or digital, and why?", "What made you pick up a camera?"],
  Model: ["What's your favorite type of shoot?", "How do you prepare before a session?", "Editorial or commercial, where do you thrive?"],
  "Content Creator": ["What platform are you most active on?", "What's your content creation process?", "Collab or solo, what do you prefer?"],
  Director: ["What's your dream project?", "Who inspires your visual style?", "Short film or feature, what's the goal?"],
  Editor: ["What's your go-to color grading style?", "Premiere, DaVinci, or Final Cut?", "What's the hardest edit you've pulled off?"],
  MUA: ["What's your signature look?", "Skincare or glam, what do you love more?", "What products can you not live without?"],
  Stylist: ["Where do you source your pieces?", "Editorial or commercial, which do you prefer?", "What's your styling philosophy?"],
  Actor: ["What type of roles do you gravitate toward?", "Stage or screen, where do you thrive?", "What's your preparation process?"],
  Videographer: ["Drone or handheld, what's your style?", "What's the most cinematic thing you've filmed?", "Client work or passion projects?"],
  Writer: ["What genres do you write in?", "Have you written for screen?", "What's your creative process like?"],
  Producer: ["What's your production style?", "Indie or studio, where do you thrive?", "What's the key to a smooth shoot?"],
  Designer: ["What's your design philosophy?", "Typography or illustration, which do you love more?", "What tools define your workflow?"],
  default: ["What's inspiring you right now?", "What are you working on?", "What's your creative dream project?"],
};

export const CITY_GEO: Record<string, {lat:number;long:number}> = {
  "Los Angeles, CA":{lat:34.05,long:-118.24},"San Francisco, CA":{lat:37.77,long:-122.42},
  "Austin, TX":{lat:30.27,long:-97.74},"Nashville, TN":{lat:36.16,long:-86.78},
  "Miami, FL":{lat:25.76,long:-80.19},"Denver, CO":{lat:39.74,long:-104.99},
  "Portland, OR":{lat:45.52,long:-122.68},"Seattle, WA":{lat:47.61,long:-122.33},
  "Chicago, IL":{lat:41.88,long:-87.63},"New York, NY":{lat:40.71,long:-74.01},
  "Atlanta, GA":{lat:33.75,long:-84.39},"Las Vegas, NV":{lat:36.17,long:-115.14},
};
